user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    upstream postgres_backend {
        server db:5432;
    }

    server {
        listen 5432;
        proxy_pass postgres_backend;
        proxy_timeout 300s;
        proxy_connect_timeout 5s;
    }
}

http{
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server{
    listen 80;
    server_name localhost;

        location /api/{

        proxy_pass http://host.docker.internal:8080/;
        set $cors_origin "http://localhost:5173";
                        if ($request_method = 'OPTIONS') {
                            add_header 'Access-Control-Allow-Origin' $cors_origin always;
                            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With, Accept, Origin' always;
                            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
                            add_header 'Access-Control-Max-Age' 86400 always; # Cache da preflight request por 1 dia
                            add_header 'Content-Length' 0; # Resposta vazia é apropriada para 204
                            # Content-Type para 204 não é estritamente necessário, mas não prejudica.
                            # add_header 'Content-Type' 'text/plain charset=UTF-8';
                            return 204; # HTTP 204 No Content - indica sucesso para preflight e termina o processamento aqui.
                        }
            add_header 'Access-Control-Allow-Origin' $cors_origin always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With, Accept, Origin' always;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}