plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
    //id 'org.graalvm.buildtools.native' version '0.10.6'
    id "org.jooq.jooq-codegen-gradle" version "3.20.3"
    id("org.springdoc.openapi-gradle-plugin") version "1.9.0"
}

ext {
    springdocVersion = "2.8.9"
}

group = 'com.marcato'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    //Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    //Spring Docs
    implementation "org.springdoc:springdoc-openapi-starter-common:${springdocVersion}"
    //Spring HATEOAS
    implementation 'org.springframework.boot:spring-boot-starter-hateoas'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    //Spring Security
    implementation "org.springframework.boot:spring-boot-starter-security"
    // ULID
    implementation group: 'com.github.f4b6a3', name: 'ulid-creator', version: '5.2.3'
    // JSON Patch
    implementation group: 'io.github.vishwakarma', name: 'zjsonpatch', version: '0.5.0'
    //Auth 0
    implementation 'com.okta.spring:okta-spring-boot-starter:3.0.5'
    // UNIREST
    implementation 'com.mashape.unirest:unirest-java:1.4.9'
    //jOOQ
    implementation 'org.jooq:jooq:3.20.3'
    implementation 'org.jooq:jooq-meta:3.20.3'
    implementation 'org.jooq:jooq-codegen:3.20.3'
    implementation "org.jooq:jooq-postgres-extensions:3.20.3"
    //UUID v7
    implementation 'com.fasterxml.uuid:java-uuid-generator:5.1.0'

    jooqCodegen 'org.postgresql:postgresql:42.7.5'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jooq {
    configuration {
        jdbc{
            driver = 'org.postgresql.Driver'
            url = 'jdbc:postgresql://localhost:5432/postgres'
            user = 'postgres'
            password = 'sukhoisu57'
        }
        generator{
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                includes = '.*'
                inputSchema = 'erp_marcato'
            }
            generate{
                pojos = true
                daos = true
                records = true
                tables = true
            }
            target{
                packageName = 'com.marcato.springmarcatoerp.entity'
                directory = "$projectDir/src/main/java"
            }
        }
    }

}

tasks.named('test') {
    useJUnitPlatform()
}
