/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.daos;


import com.marcato.springmarcatoerp.jooq.tables.EmployeesIdentifier;
import com.marcato.springmarcatoerp.jooq.tables.records.EmployeesIdentifierRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesIdentifierDao extends DAOImpl<EmployeesIdentifierRecord, com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier, Integer> {

    /**
     * Create a new EmployeesIdentifierDao without any configuration
     */
    public EmployeesIdentifierDao() {
        super(EmployeesIdentifier.EMPLOYEES_IDENTIFIER, com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier.class);
    }

    /**
     * Create a new EmployeesIdentifierDao with an attached configuration
     */
    public EmployeesIdentifierDao(Configuration configuration) {
        super(EmployeesIdentifier.EMPLOYEES_IDENTIFIER, com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier.class, configuration);
    }

    @Override
    public Integer getId(com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchById(Integer... values) {
        return fetch(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier fetchOneById(Integer value) {
        return fetchOne(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchOptionalById(Integer value) {
        return fetchOptional(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.ID, value);
    }

    /**
     * Fetch records that have <code>employeeId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchRangeOfEmployeeid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.EMPLOYEEID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>employeeId IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchByEmployeeid(Integer... values) {
        return fetch(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.EMPLOYEEID, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchRangeOfType(String lowerInclusive, String upperInclusive) {
        return fetchRange(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchByType(String... values) {
        return fetch(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.TYPE, values);
    }

    /**
     * Fetch records that have <code>identifier BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchRangeOfIdentifier(String lowerInclusive, String upperInclusive) {
        return fetchRange(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.IDENTIFIER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>identifier IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.EmployeesIdentifier> fetchByIdentifier(String... values) {
        return fetch(EmployeesIdentifier.EMPLOYEES_IDENTIFIER.IDENTIFIER, values);
    }
}
