/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.daos;


import com.marcato.springmarcatoerp.jooq.tables.Employees;
import com.marcato.springmarcatoerp.jooq.tables.records.EmployeesRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesDao extends DAOImpl<EmployeesRecord, com.marcato.springmarcatoerp.jooq.tables.pojos.Employees, Integer> {

    /**
     * Create a new EmployeesDao without any configuration
     */
    public EmployeesDao() {
        super(Employees.EMPLOYEES, com.marcato.springmarcatoerp.jooq.tables.pojos.Employees.class);
    }

    /**
     * Create a new EmployeesDao with an attached configuration
     */
    public EmployeesDao(Configuration configuration) {
        super(Employees.EMPLOYEES, com.marcato.springmarcatoerp.jooq.tables.pojos.Employees.class, configuration);
    }

    @Override
    public Integer getId(com.marcato.springmarcatoerp.jooq.tables.pojos.Employees object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchById(Integer... values) {
        return fetch(Employees.EMPLOYEES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.marcato.springmarcatoerp.jooq.tables.pojos.Employees fetchOneById(Integer value) {
        return fetchOne(Employees.EMPLOYEES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchOptionalById(Integer value) {
        return fetchOptional(Employees.EMPLOYEES.ID, value);
    }

    /**
     * Fetch records that have <code>fullName BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfFullname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.FULLNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fullName IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchByFullname(String... values) {
        return fetch(Employees.EMPLOYEES.FULLNAME, values);
    }

    /**
     * Fetch records that have <code>hireDate BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfHiredate(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.HIREDATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>hireDate IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchByHiredate(OffsetDateTime... values) {
        return fetch(Employees.EMPLOYEES.HIREDATE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchByStatus(String... values) {
        return fetch(Employees.EMPLOYEES.STATUS, values);
    }

    /**
     * Fetch records that have <code>roleId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfRoleid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.ROLEID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>roleId IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchByRoleid(Integer... values) {
        return fetch(Employees.EMPLOYEES.ROLEID, values);
    }

    /**
     * Fetch records that have <code>sectorId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfSectorid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.SECTORID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sectorId IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchBySectorid(Integer... values) {
        return fetch(Employees.EMPLOYEES.SECTORID, values);
    }

    /**
     * Fetch records that have <code>userErpId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchRangeOfUsererpid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.USERERPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>userErpId IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchByUsererpid(Integer... values) {
        return fetch(Employees.EMPLOYEES.USERERPID, values);
    }

    /**
     * Fetch a unique record that has <code>userErpId = value</code>
     */
    public com.marcato.springmarcatoerp.jooq.tables.pojos.Employees fetchOneByUsererpid(Integer value) {
        return fetchOne(Employees.EMPLOYEES.USERERPID, value);
    }

    /**
     * Fetch a unique record that has <code>userErpId = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.jooq.tables.pojos.Employees> fetchOptionalByUsererpid(Integer value) {
        return fetchOptional(Employees.EMPLOYEES.USERERPID, value);
    }
}
