/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.daos;


import com.marcato.springmarcatoerp.jooq.tables.Sector;
import com.marcato.springmarcatoerp.jooq.tables.records.SectorRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SectorDao extends DAOImpl<SectorRecord, com.marcato.springmarcatoerp.jooq.tables.pojos.Sector, Integer> {

    /**
     * Create a new SectorDao without any configuration
     */
    public SectorDao() {
        super(Sector.SECTOR, com.marcato.springmarcatoerp.jooq.tables.pojos.Sector.class);
    }

    /**
     * Create a new SectorDao with an attached configuration
     */
    public SectorDao(Configuration configuration) {
        super(Sector.SECTOR, com.marcato.springmarcatoerp.jooq.tables.pojos.Sector.class, configuration);
    }

    @Override
    public Integer getId(com.marcato.springmarcatoerp.jooq.tables.pojos.Sector object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Sector.SECTOR.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchById(Integer... values) {
        return fetch(Sector.SECTOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.marcato.springmarcatoerp.jooq.tables.pojos.Sector fetchOneById(Integer value) {
        return fetchOne(Sector.SECTOR.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchOptionalById(Integer value) {
        return fetchOptional(Sector.SECTOR.ID, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sector.SECTOR.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchByTitle(String... values) {
        return fetch(Sector.SECTOR.TITLE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Sector.SECTOR.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchByDescription(String... values) {
        return fetch(Sector.SECTOR.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>departmentId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchRangeOfDepartmentid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Sector.SECTOR.DEPARTMENTID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>departmentId IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.jooq.tables.pojos.Sector> fetchByDepartmentid(Integer... values) {
        return fetch(Sector.SECTOR.DEPARTMENTID, values);
    }
}
