server:
  port: 8080
  http2:
    enabled: true

spring:
  rsocket:
    server:
      port: 9090
      transport: websocket
      mapping-path: /rsocket
  jooq:
    sql-dialect: postgres
  threads:
    virtual:
      enabled: true
  application:
    name: Marcato ERP
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sukhoisu57
    driver-class-name: org.postgresql.Driver


logging:
  level:
    io.rsocket: DEBUG
    root: WARN
    org:
      springframework:
        web:
          socket: DEBUG
        messaging:
          rsocket: DEBUG
        security: DEBUG



okta:
  oauth2:
    issuer: https://dev-tpjedcct43j1eghk.us.auth0.com/
    audience: https://marcato.erp.com
    groups-claim: https://marcato.erp.com/groups
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
