/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.records;


import com.marcato.springmarcatoerp.jooq.tables.Views;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewsRecord extends UpdatableRecordImpl<ViewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.views.view_id</code>.
     */
    public void setViewId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.views.view_id</code>.
     */
    public UUID getViewId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>erp_marcato.views.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.views.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>erp_marcato.views.entity_key</code>.
     */
    public void setEntityKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.views.entity_key</code>.
     */
    public String getEntityKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>erp_marcato.views.data</code>.
     */
    public void setData(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.views.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>erp_marcato.views.workspace_id</code>.
     */
    public void setWorkspaceId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>erp_marcato.views.workspace_id</code>.
     */
    public UUID getWorkspaceId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewsRecord
     */
    public ViewsRecord() {
        super(Views.VIEWS);
    }

    /**
     * Create a detached, initialised ViewsRecord
     */
    public ViewsRecord(UUID viewId, String label, String entityKey, JSONB data, UUID workspaceId) {
        super(Views.VIEWS);

        setViewId(viewId);
        setLabel(label);
        setEntityKey(entityKey);
        setData(data);
        setWorkspaceId(workspaceId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewsRecord
     */
    public ViewsRecord(com.marcato.springmarcatoerp.jooq.tables.pojos.Views value) {
        super(Views.VIEWS);

        if (value != null) {
            setViewId(value.getViewId());
            setLabel(value.getLabel());
            setEntityKey(value.getEntityKey());
            setData(value.getData());
            setWorkspaceId(value.getWorkspaceId());
            resetTouchedOnNotNull();
        }
    }
}
