/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Address;
import com.marcato.springmarcatoerp.entity.tables.Company;
import com.marcato.springmarcatoerp.entity.tables.CompanyDepartmentAddress;
import com.marcato.springmarcatoerp.entity.tables.Department;
import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.UserErp;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app_db</code>
     */
    public static final AppDb APP_DB = new AppDb();

    /**
     * The table <code>app_db.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>app_db.company</code>.
     */
    public final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>app_db.company_department_address</code>.
     */
    public final CompanyDepartmentAddress COMPANY_DEPARTMENT_ADDRESS = CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS;

    /**
     * The table <code>app_db.department</code>.
     */
    public final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>app_db.employees</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>app_db.user_erp</code>.
     */
    public final UserErp USER_ERP = UserErp.USER_ERP;

    /**
     * No further instances allowed
     */
    private AppDb() {
        super(DSL.name("app_db"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            Company.COMPANY,
            CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS,
            Department.DEPARTMENT,
            Employees.EMPLOYEES,
            UserErp.USER_ERP
        );
    }
}
