/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Department;
import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.EmployeesIdentifier;
import com.marcato.springmarcatoerp.entity.tables.Role;
import com.marcato.springmarcatoerp.entity.tables.Sector;
import com.marcato.springmarcatoerp.entity.tables.UserErp;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ErpMarcato extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato</code>
     */
    public static final ErpMarcato ERP_MARCATO = new ErpMarcato();

    /**
     * The table <code>erp_marcato.department</code>.
     */
    public final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>erp_marcato.employees</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>erp_marcato.employees_identifier</code>.
     */
    public final EmployeesIdentifier EMPLOYEES_IDENTIFIER = EmployeesIdentifier.EMPLOYEES_IDENTIFIER;

    /**
     * The table <code>erp_marcato.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>erp_marcato.sector</code>.
     */
    public final Sector SECTOR = Sector.SECTOR;

    /**
     * The table <code>erp_marcato.usererp</code>.
     */
    public final UserErp USERERP = UserErp.USERERP;

    /**
     * No further instances allowed
     */
    private ErpMarcato() {
        super(DSL.name("erp_marcato"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Department.DEPARTMENT,
            Employees.EMPLOYEES,
            EmployeesIdentifier.EMPLOYEES_IDENTIFIER,
            Role.ROLE,
            Sector.SECTOR,
            UserErp.USERERP
        );
    }
}
