/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.EmployeesIdentifier;
import com.marcato.springmarcatoerp.entity.tables.Sector;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in erp_marcato.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EMPLOYEES_IDENTIFIER_EMPLOYEEID_IDX = Internal.createIndex(DSL.name("Employees_Identifier_employeeId_idx"), EmployeesIdentifier.EMPLOYEES_IDENTIFIER, new OrderField[] { EmployeesIdentifier.EMPLOYEES_IDENTIFIER.EMPLOYEEID }, false);
    public static final Index EMPLOYEES_ROLEID_IDX = Internal.createIndex(DSL.name("Employees_roleId_idx"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.ROLEID }, false);
    public static final Index EMPLOYEES_SECTORID_IDX = Internal.createIndex(DSL.name("Employees_sectorId_idx"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.SECTORID }, false);
    public static final Index EMPLOYEES_USERERPID_IDX = Internal.createIndex(DSL.name("Employees_userErpId_idx"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.USERERPID }, false);
    public static final Index SECTOR_DEPARTMENTID_IDX = Internal.createIndex(DSL.name("Sector_departmentId_idx"), Sector.SECTOR, new OrderField[] { Sector.SECTOR.DEPARTMENTID }, false);
}
