/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.UserErp;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;
import com.marcato.springmarcatoerp.entity.tables.records.UserErpRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * erp_marcato.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EmployeesRecord> UQ_IDENTIFICADOR = Internal.createUniqueKey(Employees.EMPLOYEES, DSL.name("uq_identificador"), new TableField[] { Employees.EMPLOYEES.TIPO_IDENTIFICADOR, Employees.EMPLOYEES.IDENTIFICADOR }, true);
    public static final UniqueKey<UserErpRecord> USERERP_PKEY = Internal.createUniqueKey(UserErp.USERERP, DSL.name("usererp_pkey"), new TableField[] { UserErp.USERERP.ID }, true);
    public static final UniqueKey<UserErpRecord> USERERP_USER_UUID_KEY = Internal.createUniqueKey(UserErp.USERERP, DSL.name("usererp_user_uuid_key"), new TableField[] { UserErp.USERERP.USER_UUID }, true);
}
