/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Department;
import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.EmployeesIdentifier;
import com.marcato.springmarcatoerp.entity.tables.Role;
import com.marcato.springmarcatoerp.entity.tables.Sector;
import com.marcato.springmarcatoerp.entity.tables.UserErp;
import com.marcato.springmarcatoerp.entity.tables.records.DepartmentRecord;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesIdentifierRecord;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;
import com.marcato.springmarcatoerp.entity.tables.records.RoleRecord;
import com.marcato.springmarcatoerp.entity.tables.records.SectorRecord;
import com.marcato.springmarcatoerp.entity.tables.records.UserErpRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * erp_marcato.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DepartmentRecord> DEPARTMENT_PKEY = Internal.createUniqueKey(Department.DEPARTMENT, DSL.name("department_pkey"), new TableField[] { Department.DEPARTMENT.ID }, true);
    public static final UniqueKey<EmployeesRecord> EMPLOYEES_PKEY = Internal.createUniqueKey(Employees.EMPLOYEES, DSL.name("employees_pkey"), new TableField[] { Employees.EMPLOYEES.ID }, true);
    public static final UniqueKey<EmployeesIdentifierRecord> EMPLOYEES_IDENTIFIER_PKEY = Internal.createUniqueKey(EmployeesIdentifier.EMPLOYEES_IDENTIFIER, DSL.name("employees_identifier_pkey"), new TableField[] { EmployeesIdentifier.EMPLOYEES_IDENTIFIER.ID }, true);
    public static final UniqueKey<EmployeesIdentifierRecord> UQ_IDENTIFIER = Internal.createUniqueKey(EmployeesIdentifier.EMPLOYEES_IDENTIFIER, DSL.name("uq_identifier"), new TableField[] { EmployeesIdentifier.EMPLOYEES_IDENTIFIER.TYPE, EmployeesIdentifier.EMPLOYEES_IDENTIFIER.IDENTIFIER }, true);
    public static final UniqueKey<RoleRecord> ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, DSL.name("role_pkey"), new TableField[] { Role.ROLE.ID }, true);
    public static final UniqueKey<SectorRecord> SECTOR_PKEY = Internal.createUniqueKey(Sector.SECTOR, DSL.name("sector_pkey"), new TableField[] { Sector.SECTOR.ID }, true);
    public static final UniqueKey<UserErpRecord> USERERP_PKEY = Internal.createUniqueKey(UserErp.USERERP, DSL.name("usererp_pkey"), new TableField[] { UserErp.USERERP.ID }, true);
    public static final UniqueKey<UserErpRecord> USERERP_USER_UUID_KEY = Internal.createUniqueKey(UserErp.USERERP, DSL.name("usererp_user_uuid_key"), new TableField[] { UserErp.USERERP.USER_UUID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmployeesRecord, RoleRecord> EMPLOYEES__FK_ROLE_ID = Internal.createForeignKey(Employees.EMPLOYEES, DSL.name("fk_role_id"), new TableField[] { Employees.EMPLOYEES.ROLE_ID }, Keys.ROLE_PKEY, new TableField[] { Role.ROLE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<EmployeesRecord, SectorRecord> EMPLOYEES__FK_SECTOR_ID = Internal.createForeignKey(Employees.EMPLOYEES, DSL.name("fk_sector_id"), new TableField[] { Employees.EMPLOYEES.SECTOR_ID }, Keys.SECTOR_PKEY, new TableField[] { Sector.SECTOR.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<EmployeesIdentifierRecord, EmployeesRecord> EMPLOYEES_IDENTIFIER__FK_EMPLOYEES_ID = Internal.createForeignKey(EmployeesIdentifier.EMPLOYEES_IDENTIFIER, DSL.name("fk_employees_id"), new TableField[] { EmployeesIdentifier.EMPLOYEES_IDENTIFIER.EMPLOYEE_ID }, Keys.EMPLOYEES_PKEY, new TableField[] { Employees.EMPLOYEES.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<RoleRecord, DepartmentRecord> ROLE__FK_ROLE_DEPARTMENT_ID = Internal.createForeignKey(Role.ROLE, DSL.name("fk_role_department_id"), new TableField[] { Role.ROLE.DEPARTMENT_ID }, Keys.DEPARTMENT_PKEY, new TableField[] { Department.DEPARTMENT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SectorRecord, DepartmentRecord> SECTOR__FK_SECTOR_DEPARTMENT = Internal.createForeignKey(Sector.SECTOR, DSL.name("fk_sector_department"), new TableField[] { Sector.SECTOR.DEPARTMENT_ID }, Keys.DEPARTMENT_PKEY, new TableField[] { Department.DEPARTMENT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
