/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Address;
import com.marcato.springmarcatoerp.entity.tables.Company;
import com.marcato.springmarcatoerp.entity.tables.CompanyDepartmentAddress;
import com.marcato.springmarcatoerp.entity.tables.Department;
import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.UserErp;
import com.marcato.springmarcatoerp.entity.tables.records.AddressRecord;
import com.marcato.springmarcatoerp.entity.tables.records.CompanyDepartmentAddressRecord;
import com.marcato.springmarcatoerp.entity.tables.records.CompanyRecord;
import com.marcato.springmarcatoerp.entity.tables.records.DepartmentRecord;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;
import com.marcato.springmarcatoerp.entity.tables.records.UserErpRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * app_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> ADDRESS_PKEY = Internal.createUniqueKey(Address.ADDRESS, DSL.name("address_pkey"), new TableField[] { Address.ADDRESS.ID }, true);
    public static final UniqueKey<CompanyRecord> COMPANY_PKEY = Internal.createUniqueKey(Company.COMPANY, DSL.name("company_pkey"), new TableField[] { Company.COMPANY.ID }, true);
    public static final UniqueKey<CompanyDepartmentAddressRecord> COMPANY_DEPARTMENT_ADDRESS_PKEY = Internal.createUniqueKey(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS, DSL.name("company_department_address_pkey"), new TableField[] { CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.COMPANY_ID, CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.DEPARTMENT_ID, CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.ADDRESS_ID }, true);
    public static final UniqueKey<DepartmentRecord> DEPARTMENT_PKEY = Internal.createUniqueKey(Department.DEPARTMENT, DSL.name("department_pkey"), new TableField[] { Department.DEPARTMENT.ID }, true);
    public static final UniqueKey<EmployeesRecord> EMPLOYEES_PKEY = Internal.createUniqueKey(Employees.EMPLOYEES, DSL.name("employees_pkey"), new TableField[] { Employees.EMPLOYEES.ID }, true);
    public static final UniqueKey<UserErpRecord> USER_ERP_KEYCLOAK_UUID_KEY = Internal.createUniqueKey(UserErp.USER_ERP, DSL.name("user_erp_keycloak_uuid_key"), new TableField[] { UserErp.USER_ERP.KEYCLOAK_UUID }, true);
    public static final UniqueKey<UserErpRecord> USER_ERP_PKEY = Internal.createUniqueKey(UserErp.USER_ERP, DSL.name("user_erp_pkey"), new TableField[] { UserErp.USER_ERP.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CompanyRecord, UserErpRecord> COMPANY__COMPANY_CREATED_BY_USER_ID_FKEY = Internal.createForeignKey(Company.COMPANY, DSL.name("company_created_by_user_id_fkey"), new TableField[] { Company.COMPANY.CREATED_BY_USER_ID }, Keys.USER_ERP_PKEY, new TableField[] { UserErp.USER_ERP.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CompanyDepartmentAddressRecord, AddressRecord> COMPANY_DEPARTMENT_ADDRESS__FK_ADDRESS = Internal.createForeignKey(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS, DSL.name("fk_address"), new TableField[] { CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.ADDRESS_ID }, Keys.ADDRESS_PKEY, new TableField[] { Address.ADDRESS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CompanyDepartmentAddressRecord, CompanyRecord> COMPANY_DEPARTMENT_ADDRESS__FK_COMPANY = Internal.createForeignKey(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS, DSL.name("fk_company"), new TableField[] { CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.COMPANY_ID }, Keys.COMPANY_PKEY, new TableField[] { Company.COMPANY.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CompanyDepartmentAddressRecord, DepartmentRecord> COMPANY_DEPARTMENT_ADDRESS__FK_DEPARTMENT = Internal.createForeignKey(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS, DSL.name("fk_department"), new TableField[] { CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.DEPARTMENT_ID }, Keys.DEPARTMENT_PKEY, new TableField[] { Department.DEPARTMENT.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<CompanyDepartmentAddressRecord, UserErpRecord> COMPANY_DEPARTMENT_ADDRESS__FK_MANAGER = Internal.createForeignKey(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS, DSL.name("fk_manager"), new TableField[] { CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.MANAGER_ID }, Keys.USER_ERP_PKEY, new TableField[] { UserErp.USER_ERP.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<EmployeesRecord, CompanyDepartmentAddressRecord> EMPLOYEES__FK_COMPANY_DEPARTMENT_ADDRESS = Internal.createForeignKey(Employees.EMPLOYEES, DSL.name("fk_company_department_address"), new TableField[] { Employees.EMPLOYEES.COMPANY_ID, Employees.EMPLOYEES.DEPARTMENT_ID, Employees.EMPLOYEES.ADDRESS_ID }, Keys.COMPANY_DEPARTMENT_ADDRESS_PKEY, new TableField[] { CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.COMPANY_ID, CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.DEPARTMENT_ID, CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS.ADDRESS_ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<EmployeesRecord, UserErpRecord> EMPLOYEES__FK_USER = Internal.createForeignKey(Employees.EMPLOYEES, DSL.name("fk_user"), new TableField[] { Employees.EMPLOYEES.USER_ID }, Keys.USER_ERP_PKEY, new TableField[] { UserErp.USER_ERP.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
