/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in erp_marcato.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>erp_marcato.Department_id_seq</code>
     */
    public static final Sequence<Integer> DEPARTMENT_ID_SEQ = Internal.createSequence("Department_id_seq", ErpMarcato.ERP_MARCATO, DSL.comment(""), SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>erp_marcato.Employees_id_seq</code>
     */
    public static final Sequence<Integer> EMPLOYEES_ID_SEQ = Internal.createSequence("Employees_id_seq", ErpMarcato.ERP_MARCATO, DSL.comment(""), SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>erp_marcato.Employees_Identifier_id_seq</code>
     */
    public static final Sequence<Integer> EMPLOYEES_IDENTIFIER_ID_SEQ = Internal.createSequence("Employees_Identifier_id_seq", ErpMarcato.ERP_MARCATO, DSL.comment(""), SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>erp_marcato.Role_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_ID_SEQ = Internal.createSequence("Role_id_seq", ErpMarcato.ERP_MARCATO, DSL.comment(""), SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>erp_marcato.Sector_id_seq</code>
     */
    public static final Sequence<Integer> SECTOR_ID_SEQ = Internal.createSequence("Sector_id_seq", ErpMarcato.ERP_MARCATO, DSL.comment(""), SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>erp_marcato.UserErp_id_seq</code>
     */
    public static final Sequence<Integer> USERERP_ID_SEQ = Internal.createSequence("UserErp_id_seq", ErpMarcato.ERP_MARCATO, DSL.comment(""), SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
