/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity;


import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.UserErp;


/**
 * Convenience access to all tables in erp_marcato.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>erp_marcato.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>erp_marcato.usererp</code>.
     */
    public static final UserErp USERERP = UserErp.USERERP;
}
