/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AddressDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String cepCode;
    private String country;
    private String city;
    private String state;
    private String neighborhood;
    private String street;
    private Integer number;
    private String complement;

    public AddressDTO() {}

    public AddressDTO(AddressDTO value) {
        this.id = value.id;
        this.cepCode = value.cepCode;
        this.country = value.country;
        this.city = value.city;
        this.state = value.state;
        this.neighborhood = value.neighborhood;
        this.street = value.street;
        this.number = value.number;
        this.complement = value.complement;
    }

    public AddressDTO(
        UUID id,
        String cepCode,
        String country,
        String city,
        String state,
        String neighborhood,
        String street,
        Integer number,
        String complement
    ) {
        this.id = id;
        this.cepCode = cepCode;
        this.country = country;
        this.city = city;
        this.state = state;
        this.neighborhood = neighborhood;
        this.street = street;
        this.number = number;
        this.complement = complement;
    }

    /**
     * Getter for <code>app_db.address.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>app_db.address.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>app_db.address.cep_code</code>.
     */
    public String getCepCode() {
        return this.cepCode;
    }

    /**
     * Setter for <code>app_db.address.cep_code</code>.
     */
    public void setCepCode(String cepCode) {
        this.cepCode = cepCode;
    }

    /**
     * Getter for <code>app_db.address.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>app_db.address.country</code>.
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for <code>app_db.address.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>app_db.address.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>app_db.address.state</code>.
     */
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>app_db.address.state</code>.
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for <code>app_db.address.neighborhood</code>.
     */
    public String getNeighborhood() {
        return this.neighborhood;
    }

    /**
     * Setter for <code>app_db.address.neighborhood</code>.
     */
    public void setNeighborhood(String neighborhood) {
        this.neighborhood = neighborhood;
    }

    /**
     * Getter for <code>app_db.address.street</code>.
     */
    public String getStreet() {
        return this.street;
    }

    /**
     * Setter for <code>app_db.address.street</code>.
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for <code>app_db.address.number</code>.
     */
    public Integer getNumber() {
        return this.number;
    }

    /**
     * Setter for <code>app_db.address.number</code>.
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * Getter for <code>app_db.address.complement</code>.
     */
    public String getComplement() {
        return this.complement;
    }

    /**
     * Setter for <code>app_db.address.complement</code>.
     */
    public void setComplement(String complement) {
        this.complement = complement;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AddressDTO other = (AddressDTO) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.cepCode == null) {
            if (other.cepCode != null)
                return false;
        }
        else if (!this.cepCode.equals(other.cepCode))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.neighborhood == null) {
            if (other.neighborhood != null)
                return false;
        }
        else if (!this.neighborhood.equals(other.neighborhood))
            return false;
        if (this.street == null) {
            if (other.street != null)
                return false;
        }
        else if (!this.street.equals(other.street))
            return false;
        if (this.number == null) {
            if (other.number != null)
                return false;
        }
        else if (!this.number.equals(other.number))
            return false;
        if (this.complement == null) {
            if (other.complement != null)
                return false;
        }
        else if (!this.complement.equals(other.complement))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.cepCode == null) ? 0 : this.cepCode.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.neighborhood == null) ? 0 : this.neighborhood.hashCode());
        result = prime * result + ((this.street == null) ? 0 : this.street.hashCode());
        result = prime * result + ((this.number == null) ? 0 : this.number.hashCode());
        result = prime * result + ((this.complement == null) ? 0 : this.complement.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(cepCode);
        sb.append(", ").append(country);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(neighborhood);
        sb.append(", ").append(street);
        sb.append(", ").append(number);
        sb.append(", ").append(complement);

        sb.append(")");
        return sb.toString();
    }
}
