/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Company implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String cnpj;
    private String legalName;
    private String tradeName;
    private Integer createdByUserId;

    public Company() {}

    public Company(Company value) {
        this.id = value.id;
        this.cnpj = value.cnpj;
        this.legalName = value.legalName;
        this.tradeName = value.tradeName;
        this.createdByUserId = value.createdByUserId;
    }

    public Company(
        UUID id,
        String cnpj,
        String legalName,
        String tradeName,
        Integer createdByUserId
    ) {
        this.id = id;
        this.cnpj = cnpj;
        this.legalName = legalName;
        this.tradeName = tradeName;
        this.createdByUserId = createdByUserId;
    }

    /**
     * Getter for <code>app_db.company.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>app_db.company.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>app_db.company.cnpj</code>.
     */
    public String getCnpj() {
        return this.cnpj;
    }

    /**
     * Setter for <code>app_db.company.cnpj</code>.
     */
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    /**
     * Getter for <code>app_db.company.legal_name</code>.
     */
    public String getLegalName() {
        return this.legalName;
    }

    /**
     * Setter for <code>app_db.company.legal_name</code>.
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }

    /**
     * Getter for <code>app_db.company.trade_name</code>.
     */
    public String getTradeName() {
        return this.tradeName;
    }

    /**
     * Setter for <code>app_db.company.trade_name</code>.
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }

    /**
     * Getter for <code>app_db.company.created_by_user_id</code>.
     */
    public Integer getCreatedByUserId() {
        return this.createdByUserId;
    }

    /**
     * Setter for <code>app_db.company.created_by_user_id</code>.
     */
    public void setCreatedByUserId(Integer createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Company other = (Company) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.cnpj == null) {
            if (other.cnpj != null)
                return false;
        }
        else if (!this.cnpj.equals(other.cnpj))
            return false;
        if (this.legalName == null) {
            if (other.legalName != null)
                return false;
        }
        else if (!this.legalName.equals(other.legalName))
            return false;
        if (this.tradeName == null) {
            if (other.tradeName != null)
                return false;
        }
        else if (!this.tradeName.equals(other.tradeName))
            return false;
        if (this.createdByUserId == null) {
            if (other.createdByUserId != null)
                return false;
        }
        else if (!this.createdByUserId.equals(other.createdByUserId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.cnpj == null) ? 0 : this.cnpj.hashCode());
        result = prime * result + ((this.legalName == null) ? 0 : this.legalName.hashCode());
        result = prime * result + ((this.tradeName == null) ? 0 : this.tradeName.hashCode());
        result = prime * result + ((this.createdByUserId == null) ? 0 : this.createdByUserId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Company (");

        sb.append(id);
        sb.append(", ").append(cnpj);
        sb.append(", ").append(legalName);
        sb.append(", ").append(tradeName);
        sb.append(", ").append(createdByUserId);

        sb.append(")");
        return sb.toString();
    }
}
