/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyDepartmentAddress implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID companyId;
    private UUID departmentId;
    private UUID addressId;
    private Integer managerId;

    public CompanyDepartmentAddress() {}

    public CompanyDepartmentAddress(CompanyDepartmentAddress value) {
        this.companyId = value.companyId;
        this.departmentId = value.departmentId;
        this.addressId = value.addressId;
        this.managerId = value.managerId;
    }

    public CompanyDepartmentAddress(
        UUID companyId,
        UUID departmentId,
        UUID addressId,
        Integer managerId
    ) {
        this.companyId = companyId;
        this.departmentId = departmentId;
        this.addressId = addressId;
        this.managerId = managerId;
    }

    /**
     * Getter for <code>app_db.company_department_address.company_id</code>.
     */
    public UUID getCompanyId() {
        return this.companyId;
    }

    /**
     * Setter for <code>app_db.company_department_address.company_id</code>.
     */
    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for <code>app_db.company_department_address.department_id</code>.
     */
    public UUID getDepartmentId() {
        return this.departmentId;
    }

    /**
     * Setter for <code>app_db.company_department_address.department_id</code>.
     */
    public void setDepartmentId(UUID departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * Getter for <code>app_db.company_department_address.address_id</code>.
     */
    public UUID getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>app_db.company_department_address.address_id</code>.
     */
    public void setAddressId(UUID addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>app_db.company_department_address.manager_id</code>.
     */
    public Integer getManagerId() {
        return this.managerId;
    }

    /**
     * Setter for <code>app_db.company_department_address.manager_id</code>.
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CompanyDepartmentAddress other = (CompanyDepartmentAddress) obj;
        if (this.companyId == null) {
            if (other.companyId != null)
                return false;
        }
        else if (!this.companyId.equals(other.companyId))
            return false;
        if (this.departmentId == null) {
            if (other.departmentId != null)
                return false;
        }
        else if (!this.departmentId.equals(other.departmentId))
            return false;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.managerId == null) {
            if (other.managerId != null)
                return false;
        }
        else if (!this.managerId.equals(other.managerId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.companyId == null) ? 0 : this.companyId.hashCode());
        result = prime * result + ((this.departmentId == null) ? 0 : this.departmentId.hashCode());
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.managerId == null) ? 0 : this.managerId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CompanyDepartmentAddress (");

        sb.append(companyId);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(addressId);
        sb.append(", ").append(managerId);

        sb.append(")");
        return sb.toString();
    }
}
