/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employees implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private Integer userId;
    private String email;
    private UUID companyId;
    private UUID departmentId;
    private UUID addressId;

    public Employees() {}

    public Employees(Employees value) {
        this.id = value.id;
        this.userId = value.userId;
        this.email = value.email;
        this.companyId = value.companyId;
        this.departmentId = value.departmentId;
        this.addressId = value.addressId;
    }

    public Employees(
        UUID id,
        Integer userId,
        String email,
        UUID companyId,
        UUID departmentId,
        UUID addressId
    ) {
        this.id = id;
        this.userId = userId;
        this.email = email;
        this.companyId = companyId;
        this.departmentId = departmentId;
        this.addressId = addressId;
    }

    /**
     * Getter for <code>app_db.employees.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>app_db.employees.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>app_db.employees.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>app_db.employees.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>app_db.employees.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>app_db.employees.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>app_db.employees.company_id</code>.
     */
    public UUID getCompanyId() {
        return this.companyId;
    }

    /**
     * Setter for <code>app_db.employees.company_id</code>.
     */
    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for <code>app_db.employees.department_id</code>.
     */
    public UUID getDepartmentId() {
        return this.departmentId;
    }

    /**
     * Setter for <code>app_db.employees.department_id</code>.
     */
    public void setDepartmentId(UUID departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * Getter for <code>app_db.employees.address_id</code>.
     */
    public UUID getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>app_db.employees.address_id</code>.
     */
    public void setAddressId(UUID addressId) {
        this.addressId = addressId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Employees other = (Employees) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.companyId == null) {
            if (other.companyId != null)
                return false;
        }
        else if (!this.companyId.equals(other.companyId))
            return false;
        if (this.departmentId == null) {
            if (other.departmentId != null)
                return false;
        }
        else if (!this.departmentId.equals(other.departmentId))
            return false;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.companyId == null) ? 0 : this.companyId.hashCode());
        result = prime * result + ((this.departmentId == null) ? 0 : this.departmentId.hashCode());
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(email);
        sb.append(", ").append(companyId);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(addressId);

        sb.append(")");
        return sb.toString();
    }
}
