/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import com.marcato.springmarcatoerp.entity.enums.Status;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employees implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String fullName;
    private LocalDateTime hireDate;
    private Integer roleId;
    private Status situation;
    private Long sectorId;

    public Employees() {}

    public Employees(Employees value) {
        this.id = value.id;
        this.fullName = value.fullName;
        this.hireDate = value.hireDate;
        this.roleId = value.roleId;
        this.situation = value.situation;
        this.sectorId = value.sectorId;
    }

    public Employees(
        Long id,
        String fullName,
        LocalDateTime hireDate,
        Integer roleId,
        Status situation,
        Long sectorId
    ) {
        this.id = id;
        this.fullName = fullName;
        this.hireDate = hireDate;
        this.roleId = roleId;
        this.situation = situation;
        this.sectorId = sectorId;
    }

    /**
     * Getter for <code>erp_marcato.employees.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.employees.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.employees.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>erp_marcato.employees.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>erp_marcato.employees.hire_date</code>.
     */
    public LocalDateTime getHireDate() {
        return this.hireDate;
    }

    /**
     * Setter for <code>erp_marcato.employees.hire_date</code>.
     */
    public void setHireDate(LocalDateTime hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * Getter for <code>erp_marcato.employees.role_id</code>.
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>erp_marcato.employees.role_id</code>.
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>erp_marcato.employees.situation</code>.
     */
    public Status getSituation() {
        return this.situation;
    }

    /**
     * Setter for <code>erp_marcato.employees.situation</code>.
     */
    public void setSituation(Status situation) {
        this.situation = situation;
    }

    /**
     * Getter for <code>erp_marcato.employees.sector_id</code>.
     */
    public Long getSectorId() {
        return this.sectorId;
    }

    /**
     * Setter for <code>erp_marcato.employees.sector_id</code>.
     */
    public void setSectorId(Long sectorId) {
        this.sectorId = sectorId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Employees other = (Employees) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.hireDate == null) {
            if (other.hireDate != null)
                return false;
        }
        else if (!this.hireDate.equals(other.hireDate))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        if (this.situation == null) {
            if (other.situation != null)
                return false;
        }
        else if (!this.situation.equals(other.situation))
            return false;
        if (this.sectorId == null) {
            if (other.sectorId != null)
                return false;
        }
        else if (!this.sectorId.equals(other.sectorId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.hireDate == null) ? 0 : this.hireDate.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.situation == null) ? 0 : this.situation.hashCode());
        result = prime * result + ((this.sectorId == null) ? 0 : this.sectorId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(id);
        sb.append(", ").append(fullName);
        sb.append(", ").append(hireDate);
        sb.append(", ").append(roleId);
        sb.append(", ").append(situation);
        sb.append(", ").append(sectorId);

        sb.append(")");
        return sb.toString();
    }
}
