/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employees implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String fullname;
    private OffsetDateTime hiredate;
    private String status;
    private Integer roleid;
    private Integer sectorid;
    private Integer usererpid;

    public Employees() {}

    public Employees(Employees value) {
        this.id = value.id;
        this.fullname = value.fullname;
        this.hiredate = value.hiredate;
        this.status = value.status;
        this.roleid = value.roleid;
        this.sectorid = value.sectorid;
        this.usererpid = value.usererpid;
    }

    public Employees(
        Integer id,
        String fullname,
        OffsetDateTime hiredate,
        String status,
        Integer roleid,
        Integer sectorid,
        Integer usererpid
    ) {
        this.id = id;
        this.fullname = fullname;
        this.hiredate = hiredate;
        this.status = status;
        this.roleid = roleid;
        this.sectorid = sectorid;
        this.usererpid = usererpid;
    }

    /**
     * Getter for <code>erp_marcato.Employees.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.Employees.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.Employees.fullName</code>.
     */
    public String getFullname() {
        return this.fullname;
    }

    /**
     * Setter for <code>erp_marcato.Employees.fullName</code>.
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * Getter for <code>erp_marcato.Employees.hireDate</code>.
     */
    public OffsetDateTime getHiredate() {
        return this.hiredate;
    }

    /**
     * Setter for <code>erp_marcato.Employees.hireDate</code>.
     */
    public void setHiredate(OffsetDateTime hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * Getter for <code>erp_marcato.Employees.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>erp_marcato.Employees.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>erp_marcato.Employees.roleId</code>.
     */
    public Integer getRoleid() {
        return this.roleid;
    }

    /**
     * Setter for <code>erp_marcato.Employees.roleId</code>.
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * Getter for <code>erp_marcato.Employees.sectorId</code>.
     */
    public Integer getSectorid() {
        return this.sectorid;
    }

    /**
     * Setter for <code>erp_marcato.Employees.sectorId</code>.
     */
    public void setSectorid(Integer sectorid) {
        this.sectorid = sectorid;
    }

    /**
     * Getter for <code>erp_marcato.Employees.userErpId</code>.
     */
    public Integer getUsererpid() {
        return this.usererpid;
    }

    /**
     * Setter for <code>erp_marcato.Employees.userErpId</code>.
     */
    public void setUsererpid(Integer usererpid) {
        this.usererpid = usererpid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Employees other = (Employees) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fullname == null) {
            if (other.fullname != null)
                return false;
        }
        else if (!this.fullname.equals(other.fullname))
            return false;
        if (this.hiredate == null) {
            if (other.hiredate != null)
                return false;
        }
        else if (!this.hiredate.equals(other.hiredate))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.roleid == null) {
            if (other.roleid != null)
                return false;
        }
        else if (!this.roleid.equals(other.roleid))
            return false;
        if (this.sectorid == null) {
            if (other.sectorid != null)
                return false;
        }
        else if (!this.sectorid.equals(other.sectorid))
            return false;
        if (this.usererpid == null) {
            if (other.usererpid != null)
                return false;
        }
        else if (!this.usererpid.equals(other.usererpid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fullname == null) ? 0 : this.fullname.hashCode());
        result = prime * result + ((this.hiredate == null) ? 0 : this.hiredate.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.roleid == null) ? 0 : this.roleid.hashCode());
        result = prime * result + ((this.sectorid == null) ? 0 : this.sectorid.hashCode());
        result = prime * result + ((this.usererpid == null) ? 0 : this.usererpid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(id);
        sb.append(", ").append(fullname);
        sb.append(", ").append(hiredate);
        sb.append(", ").append(status);
        sb.append(", ").append(roleid);
        sb.append(", ").append(sectorid);
        sb.append(", ").append(usererpid);

        sb.append(")");
        return sb.toString();
    }
}
