/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String fullName;
    private String tipoIdentificador;
    private String identificador;

    public EmployeesPojo() {}

    public EmployeesPojo(EmployeesPojo value) {
        this.id = value.id;
        this.fullName = value.fullName;
        this.tipoIdentificador = value.tipoIdentificador;
        this.identificador = value.identificador;
    }

    public EmployeesPojo(
        Integer id,
        String fullName,
        String tipoIdentificador,
        String identificador
    ) {
        this.id = id;
        this.fullName = fullName;
        this.tipoIdentificador = tipoIdentificador;
        this.identificador = identificador;
    }

    /**
     * Getter for <code>erp_marcato.employees.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.employees.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.employees.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>erp_marcato.employees.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>erp_marcato.employees.tipo_identificador</code>.
     */
    public String getTipoIdentificador() {
        return this.tipoIdentificador;
    }

    /**
     * Setter for <code>erp_marcato.employees.tipo_identificador</code>.
     */
    public void setTipoIdentificador(String tipoIdentificador) {
        this.tipoIdentificador = tipoIdentificador;
    }

    /**
     * Getter for <code>erp_marcato.employees.identificador</code>.
     */
    public String getIdentificador() {
        return this.identificador;
    }

    /**
     * Setter for <code>erp_marcato.employees.identificador</code>.
     */
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EmployeesPojo other = (EmployeesPojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        if (this.tipoIdentificador == null) {
            if (other.tipoIdentificador != null)
                return false;
        }
        else if (!this.tipoIdentificador.equals(other.tipoIdentificador))
            return false;
        if (this.identificador == null) {
            if (other.identificador != null)
                return false;
        }
        else if (!this.identificador.equals(other.identificador))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        result = prime * result + ((this.tipoIdentificador == null) ? 0 : this.tipoIdentificador.hashCode());
        result = prime * result + ((this.identificador == null) ? 0 : this.identificador.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employees (");

        sb.append(id);
        sb.append(", ").append(fullName);
        sb.append(", ").append(tipoIdentificador);
        sb.append(", ").append(identificador);

        sb.append(")");
        return sb.toString();
    }
}
