/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesIdentifier implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer employeeId;
    private String type;
    private String identifier;

    public EmployeesIdentifier() {}

    public EmployeesIdentifier(EmployeesIdentifier value) {
        this.id = value.id;
        this.employeeId = value.employeeId;
        this.type = value.type;
        this.identifier = value.identifier;
    }

    public EmployeesIdentifier(
        Long id,
        Integer employeeId,
        String type,
        String identifier
    ) {
        this.id = id;
        this.employeeId = employeeId;
        this.type = type;
        this.identifier = identifier;
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.employee_id</code>.
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.identifier</code>.
     */
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.identifier</code>.
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EmployeesIdentifier other = (EmployeesIdentifier) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.employeeId == null) {
            if (other.employeeId != null)
                return false;
        }
        else if (!this.employeeId.equals(other.employeeId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.identifier == null) {
            if (other.identifier != null)
                return false;
        }
        else if (!this.identifier.equals(other.identifier))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.employeeId == null) ? 0 : this.employeeId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.identifier == null) ? 0 : this.identifier.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EmployeesIdentifier (");

        sb.append(id);
        sb.append(", ").append(employeeId);
        sb.append(", ").append(type);
        sb.append(", ").append(identifier);

        sb.append(")");
        return sb.toString();
    }
}
