/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sector implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String title;
    private String description;
    private Integer departmentId;

    public Sector() {}

    public Sector(Sector value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
        this.departmentId = value.departmentId;
    }

    public Sector(
        Integer id,
        String title,
        String description,
        Integer departmentId
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.departmentId = departmentId;
    }

    /**
     * Getter for <code>erp_marcato.sector.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.sector.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.sector.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>erp_marcato.sector.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>erp_marcato.sector.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>erp_marcato.sector.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>erp_marcato.sector.department_id</code>.
     */
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    /**
     * Setter for <code>erp_marcato.sector.department_id</code>.
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sector other = (Sector) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.departmentId == null) {
            if (other.departmentId != null)
                return false;
        }
        else if (!this.departmentId.equals(other.departmentId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.departmentId == null) ? 0 : this.departmentId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sector (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(departmentId);

        sb.append(")");
        return sb.toString();
    }
}
