/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserErp implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private UUID keycloakUuid;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public UserErp() {}

    public UserErp(UserErp value) {
        this.id = value.id;
        this.keycloakUuid = value.keycloakUuid;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public UserErp(
        Integer id,
        UUID keycloakUuid,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.keycloakUuid = keycloakUuid;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>app_db.user_erp.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>app_db.user_erp.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>app_db.user_erp.keycloak_uuid</code>.
     */
    public UUID getKeycloakUuid() {
        return this.keycloakUuid;
    }

    /**
     * Setter for <code>app_db.user_erp.keycloak_uuid</code>.
     */
    public void setKeycloakUuid(UUID keycloakUuid) {
        this.keycloakUuid = keycloakUuid;
    }

    /**
     * Getter for <code>app_db.user_erp.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>app_db.user_erp.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>app_db.user_erp.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>app_db.user_erp.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserErp other = (UserErp) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.keycloakUuid == null) {
            if (other.keycloakUuid != null)
                return false;
        }
        else if (!this.keycloakUuid.equals(other.keycloakUuid))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.keycloakUuid == null) ? 0 : this.keycloakUuid.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserErp (");

        sb.append(id);
        sb.append(", ").append(keycloakUuid);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
