/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Workspaces implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private Integer userId;

    public Workspaces() {}

    public Workspaces(Workspaces value) {
        this.id = value.id;
        this.userId = value.userId;
    }

    public Workspaces(
        UUID id,
        Integer userId
    ) {
        this.id = id;
        this.userId = userId;
    }

    /**
     * Getter for <code>erp_marcato.workspaces.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.workspaces.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.workspaces.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>erp_marcato.workspaces.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Workspaces other = (Workspaces) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Workspaces (");

        sb.append(id);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
