/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.AppDb;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.CompanyDepartmentAddress.CompanyDepartmentAddressPath;
import com.marcato.springmarcatoerp.entity.tables.UserErp.UserErpPath;
import com.marcato.springmarcatoerp.entity.tables.records.CompanyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Company extends TableImpl<CompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app_db.company</code>
     */
    public static final Company COMPANY = new Company();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyRecord> getRecordType() {
        return CompanyRecord.class;
    }

    /**
     * The column <code>app_db.company.id</code>.
     */
    public final TableField<CompanyRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.company.cnpj</code>.
     */
    public final TableField<CompanyRecord, String> CNPJ = createField(DSL.name("cnpj"), SQLDataType.VARCHAR(14).nullable(false), this, "");

    /**
     * The column <code>app_db.company.legal_name</code>.
     */
    public final TableField<CompanyRecord, String> LEGAL_NAME = createField(DSL.name("legal_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>app_db.company.trade_name</code>.
     */
    public final TableField<CompanyRecord, String> TRADE_NAME = createField(DSL.name("trade_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>app_db.company.created_by_user_id</code>.
     */
    public final TableField<CompanyRecord, Integer> CREATED_BY_USER_ID = createField(DSL.name("created_by_user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Company(Name alias, Table<CompanyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Company(Name alias, Table<CompanyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>app_db.company</code> table reference
     */
    public Company(String alias) {
        this(DSL.name(alias), COMPANY);
    }

    /**
     * Create an aliased <code>app_db.company</code> table reference
     */
    public Company(Name alias) {
        this(alias, COMPANY);
    }

    /**
     * Create a <code>app_db.company</code> table reference
     */
    public Company() {
        this(DSL.name("company"), null);
    }

    public <O extends Record> Company(Table<O> path, ForeignKey<O, CompanyRecord> childPath, InverseForeignKey<O, CompanyRecord> parentPath) {
        super(path, childPath, parentPath, COMPANY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CompanyPath extends Company implements Path<CompanyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CompanyPath(Table<O> path, ForeignKey<O, CompanyRecord> childPath, InverseForeignKey<O, CompanyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CompanyPath(Name alias, Table<CompanyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CompanyPath as(String alias) {
            return new CompanyPath(DSL.name(alias), this);
        }

        @Override
        public CompanyPath as(Name alias) {
            return new CompanyPath(alias, this);
        }

        @Override
        public CompanyPath as(Table<?> alias) {
            return new CompanyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AppDb.APP_DB;
    }

    @Override
    public UniqueKey<CompanyRecord> getPrimaryKey() {
        return Keys.COMPANY_PKEY;
    }

    @Override
    public List<ForeignKey<CompanyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMPANY__COMPANY_CREATED_BY_USER_ID_FKEY);
    }

    private transient UserErpPath _userErp;

    /**
     * Get the implicit join path to the <code>app_db.user_erp</code> table.
     */
    public UserErpPath userErp() {
        if (_userErp == null)
            _userErp = new UserErpPath(this, Keys.COMPANY__COMPANY_CREATED_BY_USER_ID_FKEY, null);

        return _userErp;
    }

    private transient CompanyDepartmentAddressPath _companyDepartmentAddress;

    /**
     * Get the implicit to-many join path to the
     * <code>app_db.company_department_address</code> table
     */
    public CompanyDepartmentAddressPath companyDepartmentAddress() {
        if (_companyDepartmentAddress == null)
            _companyDepartmentAddress = new CompanyDepartmentAddressPath(this, null, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_COMPANY.getInverseKey());

        return _companyDepartmentAddress;
    }

    @Override
    public Company as(String alias) {
        return new Company(DSL.name(alias), this);
    }

    @Override
    public Company as(Name alias) {
        return new Company(alias, this);
    }

    @Override
    public Company as(Table<?> alias) {
        return new Company(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(String name) {
        return new Company(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(Name name) {
        return new Company(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Company rename(Table<?> name) {
        return new Company(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Condition condition) {
        return new Company(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Company where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Company whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
