/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.AppDb;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.Address.AddressPath;
import com.marcato.springmarcatoerp.entity.tables.Company.CompanyPath;
import com.marcato.springmarcatoerp.entity.tables.Department.DepartmentPath;
import com.marcato.springmarcatoerp.entity.tables.Employees.EmployeesPath;
import com.marcato.springmarcatoerp.entity.tables.UserErp.UserErpPath;
import com.marcato.springmarcatoerp.entity.tables.records.CompanyDepartmentAddressRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyDepartmentAddress extends TableImpl<CompanyDepartmentAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app_db.company_department_address</code>
     */
    public static final CompanyDepartmentAddress COMPANY_DEPARTMENT_ADDRESS = new CompanyDepartmentAddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyDepartmentAddressRecord> getRecordType() {
        return CompanyDepartmentAddressRecord.class;
    }

    /**
     * The column <code>app_db.company_department_address.company_id</code>.
     */
    public final TableField<CompanyDepartmentAddressRecord, UUID> COMPANY_ID = createField(DSL.name("company_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.company_department_address.department_id</code>.
     */
    public final TableField<CompanyDepartmentAddressRecord, UUID> DEPARTMENT_ID = createField(DSL.name("department_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.company_department_address.address_id</code>.
     */
    public final TableField<CompanyDepartmentAddressRecord, UUID> ADDRESS_ID = createField(DSL.name("address_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.company_department_address.manager_id</code>.
     */
    public final TableField<CompanyDepartmentAddressRecord, Integer> MANAGER_ID = createField(DSL.name("manager_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private CompanyDepartmentAddress(Name alias, Table<CompanyDepartmentAddressRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CompanyDepartmentAddress(Name alias, Table<CompanyDepartmentAddressRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>app_db.company_department_address</code> table
     * reference
     */
    public CompanyDepartmentAddress(String alias) {
        this(DSL.name(alias), COMPANY_DEPARTMENT_ADDRESS);
    }

    /**
     * Create an aliased <code>app_db.company_department_address</code> table
     * reference
     */
    public CompanyDepartmentAddress(Name alias) {
        this(alias, COMPANY_DEPARTMENT_ADDRESS);
    }

    /**
     * Create a <code>app_db.company_department_address</code> table reference
     */
    public CompanyDepartmentAddress() {
        this(DSL.name("company_department_address"), null);
    }

    public <O extends Record> CompanyDepartmentAddress(Table<O> path, ForeignKey<O, CompanyDepartmentAddressRecord> childPath, InverseForeignKey<O, CompanyDepartmentAddressRecord> parentPath) {
        super(path, childPath, parentPath, COMPANY_DEPARTMENT_ADDRESS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CompanyDepartmentAddressPath extends CompanyDepartmentAddress implements Path<CompanyDepartmentAddressRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CompanyDepartmentAddressPath(Table<O> path, ForeignKey<O, CompanyDepartmentAddressRecord> childPath, InverseForeignKey<O, CompanyDepartmentAddressRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CompanyDepartmentAddressPath(Name alias, Table<CompanyDepartmentAddressRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CompanyDepartmentAddressPath as(String alias) {
            return new CompanyDepartmentAddressPath(DSL.name(alias), this);
        }

        @Override
        public CompanyDepartmentAddressPath as(Name alias) {
            return new CompanyDepartmentAddressPath(alias, this);
        }

        @Override
        public CompanyDepartmentAddressPath as(Table<?> alias) {
            return new CompanyDepartmentAddressPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AppDb.APP_DB;
    }

    @Override
    public UniqueKey<CompanyDepartmentAddressRecord> getPrimaryKey() {
        return Keys.COMPANY_DEPARTMENT_ADDRESS_PKEY;
    }

    @Override
    public List<ForeignKey<CompanyDepartmentAddressRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COMPANY_DEPARTMENT_ADDRESS__FK_ADDRESS, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_COMPANY, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_DEPARTMENT, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_MANAGER);
    }

    private transient AddressPath _address;

    /**
     * Get the implicit join path to the <code>app_db.address</code> table.
     */
    public AddressPath address() {
        if (_address == null)
            _address = new AddressPath(this, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_ADDRESS, null);

        return _address;
    }

    private transient CompanyPath _company;

    /**
     * Get the implicit join path to the <code>app_db.company</code> table.
     */
    public CompanyPath company() {
        if (_company == null)
            _company = new CompanyPath(this, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_COMPANY, null);

        return _company;
    }

    private transient DepartmentPath _department;

    /**
     * Get the implicit join path to the <code>app_db.department</code> table.
     */
    public DepartmentPath department() {
        if (_department == null)
            _department = new DepartmentPath(this, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_DEPARTMENT, null);

        return _department;
    }

    private transient UserErpPath _userErp;

    /**
     * Get the implicit join path to the <code>app_db.user_erp</code> table.
     */
    public UserErpPath userErp() {
        if (_userErp == null)
            _userErp = new UserErpPath(this, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_MANAGER, null);

        return _userErp;
    }

    private transient EmployeesPath _employees;

    /**
     * Get the implicit to-many join path to the <code>app_db.employees</code>
     * table
     */
    public EmployeesPath employees() {
        if (_employees == null)
            _employees = new EmployeesPath(this, null, Keys.EMPLOYEES__FK_COMPANY_DEPARTMENT_ADDRESS.getInverseKey());

        return _employees;
    }

    @Override
    public CompanyDepartmentAddress as(String alias) {
        return new CompanyDepartmentAddress(DSL.name(alias), this);
    }

    @Override
    public CompanyDepartmentAddress as(Name alias) {
        return new CompanyDepartmentAddress(alias, this);
    }

    @Override
    public CompanyDepartmentAddress as(Table<?> alias) {
        return new CompanyDepartmentAddress(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyDepartmentAddress rename(String name) {
        return new CompanyDepartmentAddress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyDepartmentAddress rename(Name name) {
        return new CompanyDepartmentAddress(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyDepartmentAddress rename(Table<?> name) {
        return new CompanyDepartmentAddress(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyDepartmentAddress where(Condition condition) {
        return new CompanyDepartmentAddress(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyDepartmentAddress where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyDepartmentAddress where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyDepartmentAddress where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyDepartmentAddress where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyDepartmentAddress where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyDepartmentAddress where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyDepartmentAddress where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyDepartmentAddress whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyDepartmentAddress whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
