/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.ErpMarcato;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.Sector.SectorPath;
import com.marcato.springmarcatoerp.entity.tables.records.DepartmentRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Department extends TableImpl<DepartmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.Department</code>
     */
    public static final Department DEPARTMENT = new Department();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepartmentRecord> getRecordType() {
        return DepartmentRecord.class;
    }

    /**
     * The column <code>erp_marcato.Department.id</code>.
     */
    public final TableField<DepartmentRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('erp_marcato.\"Department_id_seq\"'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>erp_marcato.Department.title</code>.
     */
    public final TableField<DepartmentRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>erp_marcato.Department.description</code>.
     */
    public final TableField<DepartmentRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private Department(Name alias, Table<DepartmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Department(Name alias, Table<DepartmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.Department</code> table reference
     */
    public Department(String alias) {
        this(DSL.name(alias), DEPARTMENT);
    }

    /**
     * Create an aliased <code>erp_marcato.Department</code> table reference
     */
    public Department(Name alias) {
        this(alias, DEPARTMENT);
    }

    /**
     * Create a <code>erp_marcato.Department</code> table reference
     */
    public Department() {
        this(DSL.name("Department"), null);
    }

    public <O extends Record> Department(Table<O> path, ForeignKey<O, DepartmentRecord> childPath, InverseForeignKey<O, DepartmentRecord> parentPath) {
        super(path, childPath, parentPath, DEPARTMENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DepartmentPath extends Department implements Path<DepartmentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DepartmentPath(Table<O> path, ForeignKey<O, DepartmentRecord> childPath, InverseForeignKey<O, DepartmentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DepartmentPath(Name alias, Table<DepartmentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DepartmentPath as(String alias) {
            return new DepartmentPath(DSL.name(alias), this);
        }

        @Override
        public DepartmentPath as(Name alias) {
            return new DepartmentPath(alias, this);
        }

        @Override
        public DepartmentPath as(Table<?> alias) {
            return new DepartmentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public UniqueKey<DepartmentRecord> getPrimaryKey() {
        return Keys.DEPARTMENT_PKEY;
    }

    private transient SectorPath _sector;

    /**
     * Get the implicit to-many join path to the <code>erp_marcato.Sector</code>
     * table
     */
    public SectorPath sector() {
        if (_sector == null)
            _sector = new SectorPath(this, null, Keys.SECTOR__FK_DEPARTMENT.getInverseKey());

        return _sector;
    }

    @Override
    public Department as(String alias) {
        return new Department(DSL.name(alias), this);
    }

    @Override
    public Department as(Name alias) {
        return new Department(alias, this);
    }

    @Override
    public Department as(Table<?> alias) {
        return new Department(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Department rename(String name) {
        return new Department(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Department rename(Name name) {
        return new Department(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Department rename(Table<?> name) {
        return new Department(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Department where(Condition condition) {
        return new Department(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Department where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Department where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Department where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Department where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Department where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Department where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Department where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Department whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Department whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
