/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.ErpMarcato;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.enums.Status;
import com.marcato.springmarcatoerp.entity.tables.EmployeesIdentifier.EmployeesIdentifierPath;
import com.marcato.springmarcatoerp.entity.tables.Role.RolePath;
import com.marcato.springmarcatoerp.entity.tables.Sector.SectorPath;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employees extends TableImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.employees</code>
     */
    public static final Employees EMPLOYEES = new Employees();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeesRecord> getRecordType() {
        return EmployeesRecord.class;
    }

    /**
     * The column <code>erp_marcato.employees.id</code>.
     */
    public final TableField<EmployeesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>erp_marcato.employees.full_name</code>.
     */
    public final TableField<EmployeesRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>erp_marcato.employees.hire_date</code>.
     */
    public final TableField<EmployeesRecord, LocalDateTime> HIRE_DATE = createField(DSL.name("hire_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>erp_marcato.employees.role_id</code>.
     */
    public final TableField<EmployeesRecord, Integer> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>erp_marcato.employees.situation</code>.
     */
    public final TableField<EmployeesRecord, Status> SITUATION = createField(DSL.name("situation"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(Status.class), this, "");

    /**
     * The column <code>erp_marcato.employees.sector_id</code>.
     */
    public final TableField<EmployeesRecord, Long> SECTOR_ID = createField(DSL.name("sector_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Employees(Name alias, Table<EmployeesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Employees(Name alias, Table<EmployeesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.employees</code> table reference
     */
    public Employees(String alias) {
        this(DSL.name(alias), EMPLOYEES);
    }

    /**
     * Create an aliased <code>erp_marcato.employees</code> table reference
     */
    public Employees(Name alias) {
        this(alias, EMPLOYEES);
    }

    /**
     * Create a <code>erp_marcato.employees</code> table reference
     */
    public Employees() {
        this(DSL.name("employees"), null);
    }

    public <O extends Record> Employees(Table<O> path, ForeignKey<O, EmployeesRecord> childPath, InverseForeignKey<O, EmployeesRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeesPath extends Employees implements Path<EmployeesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmployeesPath(Table<O> path, ForeignKey<O, EmployeesRecord> childPath, InverseForeignKey<O, EmployeesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeesPath(Name alias, Table<EmployeesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeesPath as(String alias) {
            return new EmployeesPath(DSL.name(alias), this);
        }

        @Override
        public EmployeesPath as(Name alias) {
            return new EmployeesPath(alias, this);
        }

        @Override
        public EmployeesPath as(Table<?> alias) {
            return new EmployeesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public Identity<EmployeesRecord, Long> getIdentity() {
        return (Identity<EmployeesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmployeesRecord> getPrimaryKey() {
        return Keys.EMPLOYEES_PKEY;
    }

    @Override
    public List<ForeignKey<EmployeesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMPLOYEES__FK_ROLE_ID, Keys.EMPLOYEES__FK_SECTOR_ID);
    }

    private transient RolePath _role;

    /**
     * Get the implicit join path to the <code>erp_marcato.role</code> table.
     */
    public RolePath role() {
        if (_role == null)
            _role = new RolePath(this, Keys.EMPLOYEES__FK_ROLE_ID, null);

        return _role;
    }

    private transient SectorPath _sector;

    /**
     * Get the implicit join path to the <code>erp_marcato.sector</code> table.
     */
    public SectorPath sector() {
        if (_sector == null)
            _sector = new SectorPath(this, Keys.EMPLOYEES__FK_SECTOR_ID, null);

        return _sector;
    }

    private transient EmployeesIdentifierPath _employeesIdentifier;

    /**
     * Get the implicit to-many join path to the
     * <code>erp_marcato.employees_identifier</code> table
     */
    public EmployeesIdentifierPath employeesIdentifier() {
        if (_employeesIdentifier == null)
            _employeesIdentifier = new EmployeesIdentifierPath(this, null, Keys.EMPLOYEES_IDENTIFIER__FK_EMPLOYEES_ID.getInverseKey());

        return _employeesIdentifier;
    }

    @Override
    public Employees as(String alias) {
        return new Employees(DSL.name(alias), this);
    }

    @Override
    public Employees as(Name alias) {
        return new Employees(alias, this);
    }

    @Override
    public Employees as(Table<?> alias) {
        return new Employees(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(String name) {
        return new Employees(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Name name) {
        return new Employees(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Table<?> name) {
        return new Employees(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition condition) {
        return new Employees(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
