/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.ErpMarcato;
import com.marcato.springmarcatoerp.entity.Indexes;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.Employees.EmployeesPath;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesIdentifierRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesIdentifier extends TableImpl<EmployeesIdentifierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.Employees_Identifier</code>
     */
    public static final EmployeesIdentifier EMPLOYEES_IDENTIFIER = new EmployeesIdentifier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeesIdentifierRecord> getRecordType() {
        return EmployeesIdentifierRecord.class;
    }

    /**
     * The column <code>erp_marcato.Employees_Identifier.id</code>.
     */
    public final TableField<EmployeesIdentifierRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('erp_marcato.\"Employees_Identifier_id_seq\"'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>erp_marcato.Employees_Identifier.employeeId</code>.
     */
    public final TableField<EmployeesIdentifierRecord, Integer> EMPLOYEEID = createField(DSL.name("employeeId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>erp_marcato.Employees_Identifier.type</code>.
     */
    public final TableField<EmployeesIdentifierRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>erp_marcato.Employees_Identifier.identifier</code>.
     */
    public final TableField<EmployeesIdentifierRecord, String> IDENTIFIER = createField(DSL.name("identifier"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private EmployeesIdentifier(Name alias, Table<EmployeesIdentifierRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmployeesIdentifier(Name alias, Table<EmployeesIdentifierRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.Employees_Identifier</code> table
     * reference
     */
    public EmployeesIdentifier(String alias) {
        this(DSL.name(alias), EMPLOYEES_IDENTIFIER);
    }

    /**
     * Create an aliased <code>erp_marcato.Employees_Identifier</code> table
     * reference
     */
    public EmployeesIdentifier(Name alias) {
        this(alias, EMPLOYEES_IDENTIFIER);
    }

    /**
     * Create a <code>erp_marcato.Employees_Identifier</code> table reference
     */
    public EmployeesIdentifier() {
        this(DSL.name("Employees_Identifier"), null);
    }

    public <O extends Record> EmployeesIdentifier(Table<O> path, ForeignKey<O, EmployeesIdentifierRecord> childPath, InverseForeignKey<O, EmployeesIdentifierRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEES_IDENTIFIER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeesIdentifierPath extends EmployeesIdentifier implements Path<EmployeesIdentifierRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmployeesIdentifierPath(Table<O> path, ForeignKey<O, EmployeesIdentifierRecord> childPath, InverseForeignKey<O, EmployeesIdentifierRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeesIdentifierPath(Name alias, Table<EmployeesIdentifierRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeesIdentifierPath as(String alias) {
            return new EmployeesIdentifierPath(DSL.name(alias), this);
        }

        @Override
        public EmployeesIdentifierPath as(Name alias) {
            return new EmployeesIdentifierPath(alias, this);
        }

        @Override
        public EmployeesIdentifierPath as(Table<?> alias) {
            return new EmployeesIdentifierPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EMPLOYEES_IDENTIFIER_EMPLOYEEID_IDX);
    }

    @Override
    public UniqueKey<EmployeesIdentifierRecord> getPrimaryKey() {
        return Keys.EMPLOYEES_IDENTIFIER_PKEY;
    }

    @Override
    public List<UniqueKey<EmployeesIdentifierRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.EMPLOYEES_IDENTIFIER_EMPLOYEEID_TYPE_KEY);
    }

    @Override
    public List<ForeignKey<EmployeesIdentifierRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMPLOYEES_IDENTIFIER__FK_EMPLOYEE);
    }

    private transient EmployeesPath _employees;

    /**
     * Get the implicit join path to the <code>erp_marcato.Employees</code>
     * table.
     */
    public EmployeesPath employees() {
        if (_employees == null)
            _employees = new EmployeesPath(this, Keys.EMPLOYEES_IDENTIFIER__FK_EMPLOYEE, null);

        return _employees;
    }

    @Override
    public EmployeesIdentifier as(String alias) {
        return new EmployeesIdentifier(DSL.name(alias), this);
    }

    @Override
    public EmployeesIdentifier as(Name alias) {
        return new EmployeesIdentifier(alias, this);
    }

    @Override
    public EmployeesIdentifier as(Table<?> alias) {
        return new EmployeesIdentifier(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeesIdentifier rename(String name) {
        return new EmployeesIdentifier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeesIdentifier rename(Name name) {
        return new EmployeesIdentifier(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeesIdentifier rename(Table<?> name) {
        return new EmployeesIdentifier(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeesIdentifier where(Condition condition) {
        return new EmployeesIdentifier(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeesIdentifier where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeesIdentifier where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeesIdentifier where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeesIdentifier where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeesIdentifier where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeesIdentifier where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeesIdentifier where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeesIdentifier whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeesIdentifier whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
