/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.ErpMarcato;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employees extends TableImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.employees</code>
     */
    public static final Employees EMPLOYEES = new Employees();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeesRecord> getRecordType() {
        return EmployeesRecord.class;
    }

    /**
     * The column <code>erp_marcato.employees.id</code>.
     */
    public final TableField<EmployeesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>erp_marcato.employees.full_name</code>.
     */
    public final TableField<EmployeesRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>erp_marcato.employees.tipo_identificador</code>.
     */
    public final TableField<EmployeesRecord, String> TIPO_IDENTIFICADOR = createField(DSL.name("tipo_identificador"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>erp_marcato.employees.identificador</code>.
     */
    public final TableField<EmployeesRecord, String> IDENTIFICADOR = createField(DSL.name("identificador"), SQLDataType.VARCHAR(14).nullable(false), this, "");

    private Employees(Name alias, Table<EmployeesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Employees(Name alias, Table<EmployeesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.employees</code> table reference
     */
    public Employees(String alias) {
        this(DSL.name(alias), EMPLOYEES);
    }

    /**
     * Create an aliased <code>erp_marcato.employees</code> table reference
     */
    public Employees(Name alias) {
        this(alias, EMPLOYEES);
    }

    /**
     * Create a <code>erp_marcato.employees</code> table reference
     */
    public Employees() {
        this(DSL.name("employees"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public Identity<EmployeesRecord, Integer> getIdentity() {
        return (Identity<EmployeesRecord, Integer>) super.getIdentity();
    }

    @Override
    public List<UniqueKey<EmployeesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_IDENTIFICADOR);
    }

    @Override
    public List<Check<EmployeesRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_size_identificador"), "(((((tipo_identificador)::text = 'CPF'::text) AND (length((identificador)::text) = 11)) OR (((tipo_identificador)::text = 'CNPJ'::text) AND (length((identificador)::text) = 14))))", true),
            Internal.createCheck(this, DSL.name("chk_tipo_identificador"), "(((tipo_identificador)::text = ANY ((ARRAY['CPF'::character varying, 'CNPJ'::character varying])::text[])))", true)
        );
    }

    @Override
    public Employees as(String alias) {
        return new Employees(DSL.name(alias), this);
    }

    @Override
    public Employees as(Name alias) {
        return new Employees(alias, this);
    }

    @Override
    public Employees as(Table<?> alias) {
        return new Employees(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(String name) {
        return new Employees(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Name name) {
        return new Employees(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Table<?> name) {
        return new Employees(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition condition) {
        return new Employees(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
