/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.AppDb;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.CompanyDepartmentAddress.CompanyDepartmentAddressPath;
import com.marcato.springmarcatoerp.entity.tables.UserErp.UserErpPath;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employees extends TableImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app_db.employees</code>
     */
    public static final Employees EMPLOYEES = new Employees();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeesRecord> getRecordType() {
        return EmployeesRecord.class;
    }

    /**
     * The column <code>app_db.employees.id</code>.
     */
    public final TableField<EmployeesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.employees.user_id</code>.
     */
    public final TableField<EmployeesRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>app_db.employees.email</code>.
     */
    public final TableField<EmployeesRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>app_db.employees.company_id</code>.
     */
    public final TableField<EmployeesRecord, UUID> COMPANY_ID = createField(DSL.name("company_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.employees.department_id</code>.
     */
    public final TableField<EmployeesRecord, UUID> DEPARTMENT_ID = createField(DSL.name("department_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.employees.address_id</code>.
     */
    public final TableField<EmployeesRecord, UUID> ADDRESS_ID = createField(DSL.name("address_id"), SQLDataType.UUID.nullable(false), this, "");

    private Employees(Name alias, Table<EmployeesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Employees(Name alias, Table<EmployeesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>app_db.employees</code> table reference
     */
    public Employees(String alias) {
        this(DSL.name(alias), EMPLOYEES);
    }

    /**
     * Create an aliased <code>app_db.employees</code> table reference
     */
    public Employees(Name alias) {
        this(alias, EMPLOYEES);
    }

    /**
     * Create a <code>app_db.employees</code> table reference
     */
    public Employees() {
        this(DSL.name("employees"), null);
    }

    public <O extends Record> Employees(Table<O> path, ForeignKey<O, EmployeesRecord> childPath, InverseForeignKey<O, EmployeesRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeesPath extends Employees implements Path<EmployeesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmployeesPath(Table<O> path, ForeignKey<O, EmployeesRecord> childPath, InverseForeignKey<O, EmployeesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeesPath(Name alias, Table<EmployeesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeesPath as(String alias) {
            return new EmployeesPath(DSL.name(alias), this);
        }

        @Override
        public EmployeesPath as(Name alias) {
            return new EmployeesPath(alias, this);
        }

        @Override
        public EmployeesPath as(Table<?> alias) {
            return new EmployeesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AppDb.APP_DB;
    }

    @Override
    public UniqueKey<EmployeesRecord> getPrimaryKey() {
        return Keys.EMPLOYEES_PKEY;
    }

    @Override
    public List<ForeignKey<EmployeesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMPLOYEES__FK_COMPANY_DEPARTMENT_ADDRESS, Keys.EMPLOYEES__FK_USER);
    }

    private transient CompanyDepartmentAddressPath _companyDepartmentAddress;

    /**
     * Get the implicit join path to the
     * <code>app_db.company_department_address</code> table.
     */
    public CompanyDepartmentAddressPath companyDepartmentAddress() {
        if (_companyDepartmentAddress == null)
            _companyDepartmentAddress = new CompanyDepartmentAddressPath(this, Keys.EMPLOYEES__FK_COMPANY_DEPARTMENT_ADDRESS, null);

        return _companyDepartmentAddress;
    }

    private transient UserErpPath _userErp;

    /**
     * Get the implicit join path to the <code>app_db.user_erp</code> table.
     */
    public UserErpPath userErp() {
        if (_userErp == null)
            _userErp = new UserErpPath(this, Keys.EMPLOYEES__FK_USER, null);

        return _userErp;
    }

    @Override
    public Employees as(String alias) {
        return new Employees(DSL.name(alias), this);
    }

    @Override
    public Employees as(Name alias) {
        return new Employees(alias, this);
    }

    @Override
    public Employees as(Table<?> alias) {
        return new Employees(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(String name) {
        return new Employees(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Name name) {
        return new Employees(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employees rename(Table<?> name) {
        return new Employees(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition condition) {
        return new Employees(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employees where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employees whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
