/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.ErpMarcato;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.records.UserErpRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserErp extends TableImpl<UserErpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.usererp</code>
     */
    public static final UserErp USERERP = new UserErp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserErpRecord> getRecordType() {
        return UserErpRecord.class;
    }

    /**
     * The column <code>erp_marcato.usererp.id</code>.
     */
    public final TableField<UserErpRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>erp_marcato.usererp.user_uuid</code>.
     */
    public final TableField<UserErpRecord, UUID> USER_UUID = createField(DSL.name("user_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>erp_marcato.usererp.created_at</code>.
     */
    public final TableField<UserErpRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>erp_marcato.usererp.username</code>.
     */
    public final TableField<UserErpRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>erp_marcato.usererp.full_name</code>.
     */
    public final TableField<UserErpRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255), this, "");

    private UserErp(Name alias, Table<UserErpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserErp(Name alias, Table<UserErpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.usererp</code> table reference
     */
    public UserErp(String alias) {
        this(DSL.name(alias), USERERP);
    }

    /**
     * Create an aliased <code>erp_marcato.usererp</code> table reference
     */
    public UserErp(Name alias) {
        this(alias, USERERP);
    }

    /**
     * Create a <code>erp_marcato.usererp</code> table reference
     */
    public UserErp() {
        this(DSL.name("usererp"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public Identity<UserErpRecord, Integer> getIdentity() {
        return (Identity<UserErpRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserErpRecord> getPrimaryKey() {
        return Keys.USERERP_PKEY;
    }

    @Override
    public List<UniqueKey<UserErpRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USERERP_USER_UUID_KEY);
    }

    @Override
    public UserErp as(String alias) {
        return new UserErp(DSL.name(alias), this);
    }

    @Override
    public UserErp as(Name alias) {
        return new UserErp(alias, this);
    }

    @Override
    public UserErp as(Table<?> alias) {
        return new UserErp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserErp rename(String name) {
        return new UserErp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserErp rename(Name name) {
        return new UserErp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserErp rename(Table<?> name) {
        return new UserErp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Condition condition) {
        return new UserErp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
