/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables;


import com.marcato.springmarcatoerp.entity.AppDb;
import com.marcato.springmarcatoerp.entity.Keys;
import com.marcato.springmarcatoerp.entity.tables.Company.CompanyPath;
import com.marcato.springmarcatoerp.entity.tables.CompanyDepartmentAddress.CompanyDepartmentAddressPath;
import com.marcato.springmarcatoerp.entity.tables.Employees.EmployeesPath;
import com.marcato.springmarcatoerp.entity.tables.records.UserErpRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserErp extends TableImpl<UserErpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app_db.user_erp</code>
     */
    public static final UserErp USER_ERP = new UserErp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserErpRecord> getRecordType() {
        return UserErpRecord.class;
    }

    /**
     * The column <code>app_db.user_erp.id</code>.
     */
    public final TableField<UserErpRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>app_db.user_erp.keycloak_uuid</code>.
     */
    public final TableField<UserErpRecord, UUID> KEYCLOAK_UUID = createField(DSL.name("keycloak_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>app_db.user_erp.created_at</code>.
     */
    public final TableField<UserErpRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>app_db.user_erp.updated_at</code>.
     */
    public final TableField<UserErpRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private UserErp(Name alias, Table<UserErpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserErp(Name alias, Table<UserErpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>app_db.user_erp</code> table reference
     */
    public UserErp(String alias) {
        this(DSL.name(alias), USER_ERP);
    }

    /**
     * Create an aliased <code>app_db.user_erp</code> table reference
     */
    public UserErp(Name alias) {
        this(alias, USER_ERP);
    }

    /**
     * Create a <code>app_db.user_erp</code> table reference
     */
    public UserErp() {
        this(DSL.name("user_erp"), null);
    }

    public <O extends Record> UserErp(Table<O> path, ForeignKey<O, UserErpRecord> childPath, InverseForeignKey<O, UserErpRecord> parentPath) {
        super(path, childPath, parentPath, USER_ERP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserErpPath extends UserErp implements Path<UserErpRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserErpPath(Table<O> path, ForeignKey<O, UserErpRecord> childPath, InverseForeignKey<O, UserErpRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserErpPath(Name alias, Table<UserErpRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserErpPath as(String alias) {
            return new UserErpPath(DSL.name(alias), this);
        }

        @Override
        public UserErpPath as(Name alias) {
            return new UserErpPath(alias, this);
        }

        @Override
        public UserErpPath as(Table<?> alias) {
            return new UserErpPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AppDb.APP_DB;
    }

    @Override
    public Identity<UserErpRecord, Integer> getIdentity() {
        return (Identity<UserErpRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserErpRecord> getPrimaryKey() {
        return Keys.USER_ERP_PKEY;
    }

    @Override
    public List<UniqueKey<UserErpRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_ERP_KEYCLOAK_UUID_KEY);
    }

    private transient CompanyPath _company;

    /**
     * Get the implicit to-many join path to the <code>app_db.company</code>
     * table
     */
    public CompanyPath company() {
        if (_company == null)
            _company = new CompanyPath(this, null, Keys.COMPANY__COMPANY_CREATED_BY_USER_ID_FKEY.getInverseKey());

        return _company;
    }

    private transient CompanyDepartmentAddressPath _companyDepartmentAddress;

    /**
     * Get the implicit to-many join path to the
     * <code>app_db.company_department_address</code> table
     */
    public CompanyDepartmentAddressPath companyDepartmentAddress() {
        if (_companyDepartmentAddress == null)
            _companyDepartmentAddress = new CompanyDepartmentAddressPath(this, null, Keys.COMPANY_DEPARTMENT_ADDRESS__FK_MANAGER.getInverseKey());

        return _companyDepartmentAddress;
    }

    private transient EmployeesPath _employees;

    /**
     * Get the implicit to-many join path to the <code>app_db.employees</code>
     * table
     */
    public EmployeesPath employees() {
        if (_employees == null)
            _employees = new EmployeesPath(this, null, Keys.EMPLOYEES__FK_USER.getInverseKey());

        return _employees;
    }

    @Override
    public UserErp as(String alias) {
        return new UserErp(DSL.name(alias), this);
    }

    @Override
    public UserErp as(Name alias) {
        return new UserErp(alias, this);
    }

    @Override
    public UserErp as(Table<?> alias) {
        return new UserErp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserErp rename(String name) {
        return new UserErp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserErp rename(Name name) {
        return new UserErp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserErp rename(Table<?> name) {
        return new UserErp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Condition condition) {
        return new UserErp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserErp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserErp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
