/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Address;

import java.util.UUID;

import com.marcato.springmarcatoerp.entity.tables.pojos.AddressDTO;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app_db.address.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>app_db.address.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>app_db.address.cep_code</code>.
     */
    public void setCepCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app_db.address.cep_code</code>.
     */
    public String getCepCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app_db.address.country</code>.
     */
    public void setCountry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app_db.address.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app_db.address.city</code>.
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>app_db.address.city</code>.
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>app_db.address.state</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>app_db.address.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>app_db.address.neighborhood</code>.
     */
    public void setNeighborhood(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>app_db.address.neighborhood</code>.
     */
    public String getNeighborhood() {
        return (String) get(5);
    }

    /**
     * Setter for <code>app_db.address.street</code>.
     */
    public void setStreet(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>app_db.address.street</code>.
     */
    public String getStreet() {
        return (String) get(6);
    }

    /**
     * Setter for <code>app_db.address.number</code>.
     */
    public void setNumber(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>app_db.address.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>app_db.address.complement</code>.
     */
    public void setComplement(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>app_db.address.complement</code>.
     */
    public String getComplement() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(UUID id, String cepCode, String country, String city, String state, String neighborhood, String street, Integer number, String complement) {
        super(Address.ADDRESS);

        setId(id);
        setCepCode(cepCode);
        setCountry(country);
        setCity(city);
        setState(state);
        setNeighborhood(neighborhood);
        setStreet(street);
        setNumber(number);
        setComplement(complement);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(AddressDTO value) {
        super(Address.ADDRESS);

        if (value != null) {
            setId(value.getId());
            setCepCode(value.getCepCode());
            setCountry(value.getCountry());
            setCity(value.getCity());
            setState(value.getState());
            setNeighborhood(value.getNeighborhood());
            setStreet(value.getStreet());
            setNumber(value.getNumber());
            setComplement(value.getComplement());
            resetTouchedOnNotNull();
        }
    }
}
