/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.CompanyDepartmentAddress;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyDepartmentAddressRecord extends UpdatableRecordImpl<CompanyDepartmentAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app_db.company_department_address.company_id</code>.
     */
    public void setCompanyId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>app_db.company_department_address.company_id</code>.
     */
    public UUID getCompanyId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>app_db.company_department_address.department_id</code>.
     */
    public void setDepartmentId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>app_db.company_department_address.department_id</code>.
     */
    public UUID getDepartmentId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>app_db.company_department_address.address_id</code>.
     */
    public void setAddressId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>app_db.company_department_address.address_id</code>.
     */
    public UUID getAddressId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>app_db.company_department_address.manager_id</code>.
     */
    public void setManagerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>app_db.company_department_address.manager_id</code>.
     */
    public Integer getManagerId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, UUID, UUID> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyDepartmentAddressRecord
     */
    public CompanyDepartmentAddressRecord() {
        super(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS);
    }

    /**
     * Create a detached, initialised CompanyDepartmentAddressRecord
     */
    public CompanyDepartmentAddressRecord(UUID companyId, UUID departmentId, UUID addressId, Integer managerId) {
        super(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS);

        setCompanyId(companyId);
        setDepartmentId(departmentId);
        setAddressId(addressId);
        setManagerId(managerId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised CompanyDepartmentAddressRecord
     */
    public CompanyDepartmentAddressRecord(com.marcato.springmarcatoerp.entity.tables.pojos.CompanyDepartmentAddress value) {
        super(CompanyDepartmentAddress.COMPANY_DEPARTMENT_ADDRESS);

        if (value != null) {
            setCompanyId(value.getCompanyId());
            setDepartmentId(value.getDepartmentId());
            setAddressId(value.getAddressId());
            setManagerId(value.getManagerId());
            resetTouchedOnNotNull();
        }
    }
}
