/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Company;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyRecord extends UpdatableRecordImpl<CompanyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app_db.company.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>app_db.company.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>app_db.company.cnpj</code>.
     */
    public void setCnpj(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app_db.company.cnpj</code>.
     */
    public String getCnpj() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app_db.company.legal_name</code>.
     */
    public void setLegalName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app_db.company.legal_name</code>.
     */
    public String getLegalName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app_db.company.trade_name</code>.
     */
    public void setTradeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>app_db.company.trade_name</code>.
     */
    public String getTradeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>app_db.company.created_by_user_id</code>.
     */
    public void setCreatedByUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>app_db.company.created_by_user_id</code>.
     */
    public Integer getCreatedByUserId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyRecord
     */
    public CompanyRecord() {
        super(Company.COMPANY);
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(UUID id, String cnpj, String legalName, String tradeName, Integer createdByUserId) {
        super(Company.COMPANY);

        setId(id);
        setCnpj(cnpj);
        setLegalName(legalName);
        setTradeName(tradeName);
        setCreatedByUserId(createdByUserId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised CompanyRecord
     */
    public CompanyRecord(com.marcato.springmarcatoerp.entity.tables.pojos.Company value) {
        super(Company.COMPANY);

        if (value != null) {
            setId(value.getId());
            setCnpj(value.getCnpj());
            setLegalName(value.getLegalName());
            setTradeName(value.getTradeName());
            setCreatedByUserId(value.getCreatedByUserId());
            resetTouchedOnNotNull();
        }
    }
}
