/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Employees;

import com.marcato.springmarcatoerp.entity.tables.pojos.EmployeesPojo;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesRecord extends TableRecordImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.employees.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>erp_marcato.employees.full_name</code>.
     */
    public void setFullName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>erp_marcato.employees.tipo_identificador</code>.
     */
    public void setTipoIdentificador(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.tipo_identificador</code>.
     */
    public String getTipoIdentificador() {
        return (String) get(2);
    }

    /**
     * Setter for <code>erp_marcato.employees.identificador</code>.
     */
    public void setIdentificador(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.identificador</code>.
     */
    public String getIdentificador() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Integer id, String fullName, String tipoIdentificador, String identificador) {
        super(Employees.EMPLOYEES);

        setId(id);
        setFullName(fullName);
        setTipoIdentificador(tipoIdentificador);
        setIdentificador(identificador);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(EmployeesPojo value) {
        super(Employees.EMPLOYEES);

        if (value != null) {
            setId(value.getId());
            setFullName(value.getFullName());
            setTipoIdentificador(value.getTipoIdentificador());
            setIdentificador(value.getIdentificador());
            resetTouchedOnNotNull();
        }
    }
}
