/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Employees;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app_db.employees.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>app_db.employees.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>app_db.employees.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>app_db.employees.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>app_db.employees.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app_db.employees.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app_db.employees.company_id</code>.
     */
    public void setCompanyId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>app_db.employees.company_id</code>.
     */
    public UUID getCompanyId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>app_db.employees.department_id</code>.
     */
    public void setDepartmentId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>app_db.employees.department_id</code>.
     */
    public UUID getDepartmentId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>app_db.employees.address_id</code>.
     */
    public void setAddressId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>app_db.employees.address_id</code>.
     */
    public UUID getAddressId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(UUID id, Integer userId, String email, UUID companyId, UUID departmentId, UUID addressId) {
        super(Employees.EMPLOYEES);

        setId(id);
        setUserId(userId);
        setEmail(email);
        setCompanyId(companyId);
        setDepartmentId(departmentId);
        setAddressId(addressId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(com.marcato.springmarcatoerp.entity.tables.pojos.Employees value) {
        super(Employees.EMPLOYEES);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setEmail(value.getEmail());
            setCompanyId(value.getCompanyId());
            setDepartmentId(value.getDepartmentId());
            setAddressId(value.getAddressId());
            resetTouchedOnNotNull();
        }
    }
}
