/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.enums.Status;
import com.marcato.springmarcatoerp.entity.tables.Employees;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.employees.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>erp_marcato.employees.full_name</code>.
     */
    public void setFullName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>erp_marcato.employees.hire_date</code>.
     */
    public void setHireDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.hire_date</code>.
     */
    public LocalDateTime getHireDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>erp_marcato.employees.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>erp_marcato.employees.situation</code>.
     */
    public void setSituation(Status value) {
        set(4, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.situation</code>.
     */
    public Status getSituation() {
        return (Status) get(4);
    }

    /**
     * Setter for <code>erp_marcato.employees.sector_id</code>.
     */
    public void setSectorId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>erp_marcato.employees.sector_id</code>.
     */
    public Long getSectorId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Long id, String fullName, LocalDateTime hireDate, Integer roleId, Status situation, Long sectorId) {
        super(Employees.EMPLOYEES);

        setId(id);
        setFullName(fullName);
        setHireDate(hireDate);
        setRoleId(roleId);
        setSituation(situation);
        setSectorId(sectorId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(com.marcato.springmarcatoerp.entity.tables.pojos.Employees value) {
        super(Employees.EMPLOYEES);

        if (value != null) {
            setId(value.getId());
            setFullName(value.getFullName());
            setHireDate(value.getHireDate());
            setRoleId(value.getRoleId());
            setSituation(value.getSituation());
            setSectorId(value.getSectorId());
            resetTouchedOnNotNull();
        }
    }
}
