/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.EmployeesIdentifier;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesIdentifierRecord extends UpdatableRecordImpl<EmployeesIdentifierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.employees_identifier.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>erp_marcato.employees_identifier.identifier</code>.
     */
    public void setIdentifier(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.employees_identifier.identifier</code>.
     */
    public String getIdentifier() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesIdentifierRecord
     */
    public EmployeesIdentifierRecord() {
        super(EmployeesIdentifier.EMPLOYEES_IDENTIFIER);
    }

    /**
     * Create a detached, initialised EmployeesIdentifierRecord
     */
    public EmployeesIdentifierRecord(Long id, Integer employeeId, String type, String identifier) {
        super(EmployeesIdentifier.EMPLOYEES_IDENTIFIER);

        setId(id);
        setEmployeeId(employeeId);
        setType(type);
        setIdentifier(identifier);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised EmployeesIdentifierRecord
     */
    public EmployeesIdentifierRecord(com.marcato.springmarcatoerp.entity.tables.pojos.EmployeesIdentifier value) {
        super(EmployeesIdentifier.EMPLOYEES_IDENTIFIER);

        if (value != null) {
            setId(value.getId());
            setEmployeeId(value.getEmployeeId());
            setType(value.getType());
            setIdentifier(value.getIdentifier());
            resetTouchedOnNotNull();
        }
    }
}
