/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Role;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.role.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>erp_marcato.role.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.role.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>erp_marcato.role.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.role.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>erp_marcato.role.department_id</code>.
     */
    public void setDepartmentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.role.department_id</code>.
     */
    public Integer getDepartmentId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Long id, String title, String description, Integer departmentId) {
        super(Role.ROLE);

        setId(id);
        setTitle(title);
        setDescription(description);
        setDepartmentId(departmentId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(com.marcato.springmarcatoerp.entity.tables.pojos.Role value) {
        super(Role.ROLE);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
            setDepartmentId(value.getDepartmentId());
            resetTouchedOnNotNull();
        }
    }
}
