/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Sector;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SectorRecord extends UpdatableRecordImpl<SectorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.sector.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.sector.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>erp_marcato.sector.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.sector.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>erp_marcato.sector.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.sector.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>erp_marcato.sector.department_id</code>.
     */
    public void setDepartmentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.sector.department_id</code>.
     */
    public Integer getDepartmentId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SectorRecord
     */
    public SectorRecord() {
        super(Sector.SECTOR);
    }

    /**
     * Create a detached, initialised SectorRecord
     */
    public SectorRecord(Integer id, String title, String description, Integer departmentId) {
        super(Sector.SECTOR);

        setId(id);
        setTitle(title);
        setDescription(description);
        setDepartmentId(departmentId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SectorRecord
     */
    public SectorRecord(com.marcato.springmarcatoerp.entity.tables.pojos.Sector value) {
        super(Sector.SECTOR);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
            setDepartmentId(value.getDepartmentId());
            resetTouchedOnNotNull();
        }
    }
}
