/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Usererp;

import java.time.OffsetDateTime;
import java.util.UUID;

import com.marcato.springmarcatoerp.entity.tables.pojos.UsererpPojo;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsererpRecord extends UpdatableRecordImpl<UsererpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.UserErp.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.UserErp.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>erp_marcato.UserErp.user_uuid</code>.
     */
    public void setUserUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.UserErp.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>erp_marcato.UserErp.createdAt</code>.
     */
    public void setCreatedat(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>erp_marcato.UserErp.createdAt</code>.
     */
    public OffsetDateTime getCreatedat() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>erp_marcato.UserErp.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>erp_marcato.UserErp.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>erp_marcato.UserErp.full_name</code>.
     */
    public void setFullName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>erp_marcato.UserErp.full_name</code>.
     */
    public String getFullName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsererpRecord
     */
    public UsererpRecord() {
        super(Usererp.USERERP);
    }

    /**
     * Create a detached, initialised UsererpRecord
     */
    public UsererpRecord(Integer id, UUID userUuid, OffsetDateTime createdat, String username, String fullName) {
        super(Usererp.USERERP);

        setId(id);
        setUserUuid(userUuid);
        setCreatedat(createdat);
        setUsername(username);
        setFullName(fullName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UsererpRecord
     */
    public UsererpRecord(UsererpPojo value) {
        super(Usererp.USERERP);

        if (value != null) {
            setId(value.getId());
            setUserUuid(value.getUserUuid());
            setCreatedat(value.getCreatedat());
            setUsername(value.getUsername());
            setFullName(value.getFullName());
            resetTouchedOnNotNull();
        }
    }
}
