/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.UserErp;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserErpRecord extends UpdatableRecordImpl<UserErpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app_db.user_erp.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>app_db.user_erp.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app_db.user_erp.keycloak_uuid</code>.
     */
    public void setKeycloakUuid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>app_db.user_erp.keycloak_uuid</code>.
     */
    public UUID getKeycloakUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>app_db.user_erp.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>app_db.user_erp.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>app_db.user_erp.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>app_db.user_erp.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserErpRecord
     */
    public UserErpRecord() {
        super(UserErp.USER_ERP);
    }

    /**
     * Create a detached, initialised UserErpRecord
     */
    public UserErpRecord(Integer id, UUID keycloakUuid, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(UserErp.USER_ERP);

        setId(id);
        setKeycloakUuid(keycloakUuid);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserErpRecord
     */
    public UserErpRecord(com.marcato.springmarcatoerp.entity.tables.pojos.UserErp value) {
        super(UserErp.USER_ERP);

        if (value != null) {
            setId(value.getId());
            setKeycloakUuid(value.getKeycloakUuid());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
