/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.records;


import com.marcato.springmarcatoerp.entity.tables.Workspaces;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkspacesRecord extends UpdatableRecordImpl<WorkspacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>erp_marcato.workspaces.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>erp_marcato.workspaces.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>erp_marcato.workspaces.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>erp_marcato.workspaces.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkspacesRecord
     */
    public WorkspacesRecord() {
        super(Workspaces.WORKSPACES);
    }

    /**
     * Create a detached, initialised WorkspacesRecord
     */
    public WorkspacesRecord(UUID id, Integer userId) {
        super(Workspaces.WORKSPACES);

        setId(id);
        setUserId(userId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised WorkspacesRecord
     */
    public WorkspacesRecord(com.marcato.springmarcatoerp.entity.tables.pojos.Workspaces value) {
        super(Workspaces.WORKSPACES);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            resetTouchedOnNotNull();
        }
    }
}
