/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.daos;


import com.marcato.springmarcatoerp.entity.tables.Department;
import com.marcato.springmarcatoerp.entity.tables.records.DepartmentRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DepartmentDao extends DAOImpl<DepartmentRecord, com.marcato.springmarcatoerp.entity.tables.pojos.Department, Integer> {

    /**
     * Create a new DepartmentDao without any configuration
     */
    public DepartmentDao() {
        super(Department.DEPARTMENT, com.marcato.springmarcatoerp.entity.tables.pojos.Department.class);
    }

    /**
     * Create a new DepartmentDao with an attached configuration
     */
    public DepartmentDao(Configuration configuration) {
        super(Department.DEPARTMENT, com.marcato.springmarcatoerp.entity.tables.pojos.Department.class, configuration);
    }

    @Override
    public Integer getId(com.marcato.springmarcatoerp.entity.tables.pojos.Department object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Department.DEPARTMENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchById(Integer... values) {
        return fetch(Department.DEPARTMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.marcato.springmarcatoerp.entity.tables.pojos.Department fetchOneById(Integer value) {
        return fetchOne(Department.DEPARTMENT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchOptionalById(Integer value) {
        return fetchOptional(Department.DEPARTMENT.ID, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Department.DEPARTMENT.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchByTitle(String... values) {
        return fetch(Department.DEPARTMENT.TITLE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Department.DEPARTMENT.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Department> fetchByDescription(String... values) {
        return fetch(Department.DEPARTMENT.DESCRIPTION, values);
    }
}
