/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.daos;


import com.marcato.springmarcatoerp.entity.enums.Status;
import com.marcato.springmarcatoerp.entity.tables.Employees;
import com.marcato.springmarcatoerp.entity.tables.records.EmployeesRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesDao extends DAOImpl<EmployeesRecord, com.marcato.springmarcatoerp.entity.tables.pojos.Employees, Long> {

    /**
     * Create a new EmployeesDao without any configuration
     */
    public EmployeesDao() {
        super(Employees.EMPLOYEES, com.marcato.springmarcatoerp.entity.tables.pojos.Employees.class);
    }

    /**
     * Create a new EmployeesDao with an attached configuration
     */
    public EmployeesDao(Configuration configuration) {
        super(Employees.EMPLOYEES, com.marcato.springmarcatoerp.entity.tables.pojos.Employees.class, configuration);
    }

    @Override
    public Long getId(com.marcato.springmarcatoerp.entity.tables.pojos.Employees object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchById(Long... values) {
        return fetch(Employees.EMPLOYEES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.marcato.springmarcatoerp.entity.tables.pojos.Employees fetchOneById(Long value) {
        return fetchOne(Employees.EMPLOYEES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchOptionalById(Long value) {
        return fetchOptional(Employees.EMPLOYEES.ID, value);
    }

    /**
     * Fetch records that have <code>full_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchRangeOfFullName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.FULL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchByFullName(String... values) {
        return fetch(Employees.EMPLOYEES.FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>hire_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchRangeOfHireDate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.HIRE_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>hire_date IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchByHireDate(LocalDateTime... values) {
        return fetch(Employees.EMPLOYEES.HIRE_DATE, values);
    }

    /**
     * Fetch records that have <code>role_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchRangeOfRoleId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.ROLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchByRoleId(Integer... values) {
        return fetch(Employees.EMPLOYEES.ROLE_ID, values);
    }

    /**
     * Fetch records that have <code>situation BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchRangeOfSituation(Status lowerInclusive, Status upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.SITUATION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>situation IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchBySituation(Status... values) {
        return fetch(Employees.EMPLOYEES.SITUATION, values);
    }

    /**
     * Fetch records that have <code>sector_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchRangeOfSectorId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Employees.EMPLOYEES.SECTOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sector_id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Employees> fetchBySectorId(Long... values) {
        return fetch(Employees.EMPLOYEES.SECTOR_ID, values);
    }
}
