/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.daos;


import com.marcato.springmarcatoerp.entity.tables.Role;
import com.marcato.springmarcatoerp.entity.tables.records.RoleRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleDao extends DAOImpl<RoleRecord, com.marcato.springmarcatoerp.entity.tables.pojos.Role, Integer> {

    /**
     * Create a new RoleDao without any configuration
     */
    public RoleDao() {
        super(Role.ROLE, com.marcato.springmarcatoerp.entity.tables.pojos.Role.class);
    }

    /**
     * Create a new RoleDao with an attached configuration
     */
    public RoleDao(Configuration configuration) {
        super(Role.ROLE, com.marcato.springmarcatoerp.entity.tables.pojos.Role.class, configuration);
    }

    @Override
    public Integer getId(com.marcato.springmarcatoerp.entity.tables.pojos.Role object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Role.ROLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchById(Integer... values) {
        return fetch(Role.ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.marcato.springmarcatoerp.entity.tables.pojos.Role fetchOneById(Integer value) {
        return fetchOne(Role.ROLE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchOptionalById(Integer value) {
        return fetchOptional(Role.ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Role.ROLE.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchByTitle(String... values) {
        return fetch(Role.ROLE.TITLE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Role.ROLE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchByDescription(String... values) {
        return fetch(Role.ROLE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>level BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchRangeOfLevel(String lowerInclusive, String upperInclusive) {
        return fetchRange(Role.ROLE.LEVEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>level IN (values)</code>
     */
    public List<com.marcato.springmarcatoerp.entity.tables.pojos.Role> fetchByLevel(String... values) {
        return fetch(Role.ROLE.LEVEL, values);
    }
}
