/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.tables.daos;


import com.marcato.springmarcatoerp.entity.tables.UserErp;
import com.marcato.springmarcatoerp.entity.tables.pojos.UserErpPojo;
import com.marcato.springmarcatoerp.entity.tables.records.UserErpRecord;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserErpDao extends DAOImpl<UserErpRecord, UserErpPojo, Integer> {

    /**
     * Create a new UsererpDao without any configuration
     */
    public UserErpDao() {
        super(UserErp.USERERP, UserErpPojo.class);
    }

    /**
     * Create a new UsererpDao with an attached configuration
     */
    public UserErpDao(Configuration configuration) {
        super(UserErp.USERERP, UserErpPojo.class, configuration);
    }

    @Override
    public Integer getId(UserErpPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserErpPojo> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(UserErp.USERERP.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<UserErpPojo> fetchById(Integer... values) {
        return fetch(UserErp.USERERP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public UserErpPojo fetchOneById(Integer value) {
        return fetchOne(UserErp.USERERP.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<UserErpPojo> fetchOptionalById(Integer value) {
        return fetchOptional(UserErp.USERERP.ID, value);
    }

    /**
     * Fetch records that have <code>user_uuid BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserErpPojo> fetchRangeOfUserUuid(UUID lowerInclusive, UUID upperInclusive) {
        return fetchRange(UserErp.USERERP.USER_UUID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_uuid IN (values)</code>
     */
    public List<UserErpPojo> fetchByUserUuid(UUID... values) {
        return fetch(UserErp.USERERP.USER_UUID, values);
    }

    /**
     * Fetch a unique record that has <code>user_uuid = value</code>
     */
    public UserErpPojo fetchOneByUserUuid(UUID value) {
        return fetchOne(UserErp.USERERP.USER_UUID, value);
    }

    /**
     * Fetch a unique record that has <code>user_uuid = value</code>
     */
    public Optional<UserErpPojo> fetchOptionalByUserUuid(UUID value) {
        return fetchOptional(UserErp.USERERP.USER_UUID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserErpPojo> fetchRangeOfCreatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(UserErp.USERERP.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<UserErpPojo> fetchByCreatedAt(OffsetDateTime... values) {
        return fetch(UserErp.USERERP.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserErpPojo> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserErp.USERERP.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<UserErpPojo> fetchByUsername(String... values) {
        return fetch(UserErp.USERERP.USERNAME, values);
    }

    /**
     * Fetch records that have <code>full_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<UserErpPojo> fetchRangeOfFullName(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserErp.USERERP.FULL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<UserErpPojo> fetchByFullName(String... values) {
        return fetch(UserErp.USERERP.FULL_NAME, values);
    }
}
