/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables;


import com.marcato.springmarcatoerp.jooq.ErpMarcato;
import com.marcato.springmarcatoerp.jooq.Indexes;
import com.marcato.springmarcatoerp.jooq.Keys;
import com.marcato.springmarcatoerp.jooq.tables.Department.DepartmentPath;
import com.marcato.springmarcatoerp.jooq.tables.Employees.EmployeesPath;
import com.marcato.springmarcatoerp.jooq.tables.records.SectorRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sector extends TableImpl<SectorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.Sector</code>
     */
    public static final Sector SECTOR = new Sector();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SectorRecord> getRecordType() {
        return SectorRecord.class;
    }

    /**
     * The column <code>erp_marcato.Sector.id</code>.
     */
    public final TableField<SectorRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('erp_marcato.\"Sector_id_seq\"'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>erp_marcato.Sector.title</code>.
     */
    public final TableField<SectorRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>erp_marcato.Sector.description</code>.
     */
    public final TableField<SectorRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>erp_marcato.Sector.departmentId</code>.
     */
    public final TableField<SectorRecord, Integer> DEPARTMENTID = createField(DSL.name("departmentId"), SQLDataType.INTEGER.nullable(false), this, "");

    private Sector(Name alias, Table<SectorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sector(Name alias, Table<SectorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.Sector</code> table reference
     */
    public Sector(String alias) {
        this(DSL.name(alias), SECTOR);
    }

    /**
     * Create an aliased <code>erp_marcato.Sector</code> table reference
     */
    public Sector(Name alias) {
        this(alias, SECTOR);
    }

    /**
     * Create a <code>erp_marcato.Sector</code> table reference
     */
    public Sector() {
        this(DSL.name("Sector"), null);
    }

    public <O extends Record> Sector(Table<O> path, ForeignKey<O, SectorRecord> childPath, InverseForeignKey<O, SectorRecord> parentPath) {
        super(path, childPath, parentPath, SECTOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SectorPath extends Sector implements Path<SectorRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SectorPath(Table<O> path, ForeignKey<O, SectorRecord> childPath, InverseForeignKey<O, SectorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SectorPath(Name alias, Table<SectorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SectorPath as(String alias) {
            return new SectorPath(DSL.name(alias), this);
        }

        @Override
        public SectorPath as(Name alias) {
            return new SectorPath(alias, this);
        }

        @Override
        public SectorPath as(Table<?> alias) {
            return new SectorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SECTOR_DEPARTMENTID_IDX);
    }

    @Override
    public UniqueKey<SectorRecord> getPrimaryKey() {
        return Keys.SECTOR_PKEY;
    }

    @Override
    public List<ForeignKey<SectorRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SECTOR__FK_DEPARTMENT);
    }

    private transient DepartmentPath _department;

    /**
     * Get the implicit join path to the <code>erp_marcato.Department</code>
     * table.
     */
    public DepartmentPath department() {
        if (_department == null)
            _department = new DepartmentPath(this, Keys.SECTOR__FK_DEPARTMENT, null);

        return _department;
    }

    private transient EmployeesPath _employees;

    /**
     * Get the implicit to-many join path to the
     * <code>erp_marcato.Employees</code> table
     */
    public EmployeesPath employees() {
        if (_employees == null)
            _employees = new EmployeesPath(this, null, Keys.EMPLOYEES__FK_SECTOR.getInverseKey());

        return _employees;
    }

    @Override
    public Sector as(String alias) {
        return new Sector(DSL.name(alias), this);
    }

    @Override
    public Sector as(Name alias) {
        return new Sector(alias, this);
    }

    @Override
    public Sector as(Table<?> alias) {
        return new Sector(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sector rename(String name) {
        return new Sector(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sector rename(Name name) {
        return new Sector(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sector rename(Table<?> name) {
        return new Sector(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sector where(Condition condition) {
        return new Sector(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sector where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sector where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sector where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sector where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sector where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sector where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sector where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sector whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sector whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
