/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables;


import com.marcato.springmarcatoerp.jooq.ErpMarcato;
import com.marcato.springmarcatoerp.jooq.Keys;
import com.marcato.springmarcatoerp.jooq.tables.Employees.EmployeesPath;
import com.marcato.springmarcatoerp.jooq.tables.Workspaces.WorkspacesPath;
import com.marcato.springmarcatoerp.jooq.tables.records.UsererpRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Usererp extends TableImpl<UsererpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>erp_marcato.UserErp</code>
     */
    public static final Usererp USERERP = new Usererp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsererpRecord> getRecordType() {
        return UsererpRecord.class;
    }

    /**
     * The column <code>erp_marcato.UserErp.id</code>.
     */
    public final TableField<UsererpRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('erp_marcato.\"UserErp_id_seq\"'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>erp_marcato.UserErp.user_uuid</code>.
     */
    public final TableField<UsererpRecord, UUID> USER_UUID = createField(DSL.name("user_uuid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>erp_marcato.UserErp.createdAt</code>.
     */
    public final TableField<UsererpRecord, OffsetDateTime> CREATEDAT = createField(DSL.name("createdAt"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>erp_marcato.UserErp.username</code>.
     */
    public final TableField<UsererpRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>erp_marcato.UserErp.full_name</code>.
     */
    public final TableField<UsererpRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(255), this, "");

    private Usererp(Name alias, Table<UsererpRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Usererp(Name alias, Table<UsererpRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>erp_marcato.UserErp</code> table reference
     */
    public Usererp(String alias) {
        this(DSL.name(alias), USERERP);
    }

    /**
     * Create an aliased <code>erp_marcato.UserErp</code> table reference
     */
    public Usererp(Name alias) {
        this(alias, USERERP);
    }

    /**
     * Create a <code>erp_marcato.UserErp</code> table reference
     */
    public Usererp() {
        this(DSL.name("UserErp"), null);
    }

    public <O extends Record> Usererp(Table<O> path, ForeignKey<O, UsererpRecord> childPath, InverseForeignKey<O, UsererpRecord> parentPath) {
        super(path, childPath, parentPath, USERERP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UsererpPath extends Usererp implements Path<UsererpRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UsererpPath(Table<O> path, ForeignKey<O, UsererpRecord> childPath, InverseForeignKey<O, UsererpRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UsererpPath(Name alias, Table<UsererpRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UsererpPath as(String alias) {
            return new UsererpPath(DSL.name(alias), this);
        }

        @Override
        public UsererpPath as(Name alias) {
            return new UsererpPath(alias, this);
        }

        @Override
        public UsererpPath as(Table<?> alias) {
            return new UsererpPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ErpMarcato.ERP_MARCATO;
    }

    @Override
    public UniqueKey<UsererpRecord> getPrimaryKey() {
        return Keys.USERERP_PKEY;
    }

    @Override
    public List<UniqueKey<UsererpRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USERERP_USER_UUID_KEY, Keys.USERERP_USERNAME_KEY);
    }

    private transient EmployeesPath _employees;

    /**
     * Get the implicit to-many join path to the
     * <code>erp_marcato.Employees</code> table
     */
    public EmployeesPath employees() {
        if (_employees == null)
            _employees = new EmployeesPath(this, null, Keys.EMPLOYEES__FK_USER_ERP.getInverseKey());

        return _employees;
    }

    private transient WorkspacesPath _workspaces;

    /**
     * Get the implicit to-many join path to the
     * <code>erp_marcato.workspaces</code> table
     */
    public WorkspacesPath workspaces() {
        if (_workspaces == null)
            _workspaces = new WorkspacesPath(this, null, Keys.WORKSPACES__WORKSPACES_USER_ID_FKEY.getInverseKey());

        return _workspaces;
    }

    @Override
    public Usererp as(String alias) {
        return new Usererp(DSL.name(alias), this);
    }

    @Override
    public Usererp as(Name alias) {
        return new Usererp(alias, this);
    }

    @Override
    public Usererp as(Table<?> alias) {
        return new Usererp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Usererp rename(String name) {
        return new Usererp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usererp rename(Name name) {
        return new Usererp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usererp rename(Table<?> name) {
        return new Usererp(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usererp where(Condition condition) {
        return new Usererp(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usererp where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usererp where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usererp where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usererp where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usererp where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usererp where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usererp where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usererp whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usererp whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
