/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DepartmentPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String title;
    private String description;

    public DepartmentPojo() {}

    public DepartmentPojo(DepartmentPojo value) {
        this.id = value.id;
        this.title = value.title;
        this.description = value.description;
    }

    public DepartmentPojo(
        Integer id,
        String title,
        String description
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
    }

    /**
     * Getter for <code>erp_marcato.Department.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.Department.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.Department.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>erp_marcato.Department.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>erp_marcato.Department.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>erp_marcato.Department.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DepartmentPojo other = (DepartmentPojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Department (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
