/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeesIdentifier implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer employeeid;
    private String type;
    private String identifier;

    public EmployeesIdentifier() {}

    public EmployeesIdentifier(EmployeesIdentifier value) {
        this.id = value.id;
        this.employeeid = value.employeeid;
        this.type = value.type;
        this.identifier = value.identifier;
    }

    public EmployeesIdentifier(
        Integer id,
        Integer employeeid,
        String type,
        String identifier
    ) {
        this.id = id;
        this.employeeid = employeeid;
        this.type = type;
        this.identifier = identifier;
    }

    /**
     * Getter for <code>erp_marcato.Employees_Identifier.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.Employees_Identifier.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.Employees_Identifier.employeeId</code>.
     */
    public Integer getEmployeeid() {
        return this.employeeid;
    }

    /**
     * Setter for <code>erp_marcato.Employees_Identifier.employeeId</code>.
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * Getter for <code>erp_marcato.Employees_Identifier.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>erp_marcato.Employees_Identifier.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>erp_marcato.Employees_Identifier.identifier</code>.
     */
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * Setter for <code>erp_marcato.Employees_Identifier.identifier</code>.
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EmployeesIdentifier other = (EmployeesIdentifier) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.employeeid == null) {
            if (other.employeeid != null)
                return false;
        }
        else if (!this.employeeid.equals(other.employeeid))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.identifier == null) {
            if (other.identifier != null)
                return false;
        }
        else if (!this.identifier.equals(other.identifier))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.employeeid == null) ? 0 : this.employeeid.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.identifier == null) ? 0 : this.identifier.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EmployeesIdentifier (");

        sb.append(id);
        sb.append(", ").append(employeeid);
        sb.append(", ").append(type);
        sb.append(", ").append(identifier);

        sb.append(")");
        return sb.toString();
    }
}
