/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsererpPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private UUID userUuid;
    private OffsetDateTime createdat;
    private String username;
    private String fullName;

    public UsererpPojo() {}

    public UsererpPojo(UsererpPojo value) {
        this.id = value.id;
        this.userUuid = value.userUuid;
        this.createdat = value.createdat;
        this.username = value.username;
        this.fullName = value.fullName;
    }

    public UsererpPojo(
        Integer id,
        UUID userUuid,
        OffsetDateTime createdat,
        String username,
        String fullName
    ) {
        this.id = id;
        this.userUuid = userUuid;
        this.createdat = createdat;
        this.username = username;
        this.fullName = fullName;
    }

    /**
     * Getter for <code>erp_marcato.UserErp.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>erp_marcato.UserErp.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>erp_marcato.UserErp.user_uuid</code>.
     */
    public UUID getUserUuid() {
        return this.userUuid;
    }

    /**
     * Setter for <code>erp_marcato.UserErp.user_uuid</code>.
     */
    public void setUserUuid(UUID userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * Getter for <code>erp_marcato.UserErp.createdAt</code>.
     */
    public OffsetDateTime getCreatedat() {
        return this.createdat;
    }

    /**
     * Setter for <code>erp_marcato.UserErp.createdAt</code>.
     */
    public void setCreatedat(OffsetDateTime createdat) {
        this.createdat = createdat;
    }

    /**
     * Getter for <code>erp_marcato.UserErp.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>erp_marcato.UserErp.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>erp_marcato.UserErp.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>erp_marcato.UserErp.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UsererpPojo other = (UsererpPojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userUuid == null) {
            if (other.userUuid != null)
                return false;
        }
        else if (!this.userUuid.equals(other.userUuid))
            return false;
        if (this.createdat == null) {
            if (other.createdat != null)
                return false;
        }
        else if (!this.createdat.equals(other.createdat))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.fullName == null) {
            if (other.fullName != null)
                return false;
        }
        else if (!this.fullName.equals(other.fullName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userUuid == null) ? 0 : this.userUuid.hashCode());
        result = prime * result + ((this.createdat == null) ? 0 : this.createdat.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.fullName == null) ? 0 : this.fullName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usererp (");

        sb.append(id);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(createdat);
        sb.append(", ").append(username);
        sb.append(", ").append(fullName);

        sb.append(")");
        return sb.toString();
    }
}
