/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Views implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID viewId;
    private String label;
    private String entityKey;
    private JSONB data;
    private UUID workspaceId;

    public Views() {}

    public Views(Views value) {
        this.viewId = value.viewId;
        this.label = value.label;
        this.entityKey = value.entityKey;
        this.data = value.data;
        this.workspaceId = value.workspaceId;
    }

    public Views(
        UUID viewId,
        String label,
        String entityKey,
        JSONB data,
        UUID workspaceId
    ) {
        this.viewId = viewId;
        this.label = label;
        this.entityKey = entityKey;
        this.data = data;
        this.workspaceId = workspaceId;
    }

    /**
     * Getter for <code>erp_marcato.views.view_id</code>.
     */
    public UUID getViewId() {
        return this.viewId;
    }

    /**
     * Setter for <code>erp_marcato.views.view_id</code>.
     */
    public void setViewId(UUID viewId) {
        this.viewId = viewId;
    }

    /**
     * Getter for <code>erp_marcato.views.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>erp_marcato.views.label</code>.
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * Getter for <code>erp_marcato.views.entity_key</code>.
     */
    public String getEntityKey() {
        return this.entityKey;
    }

    /**
     * Setter for <code>erp_marcato.views.entity_key</code>.
     */
    public void setEntityKey(String entityKey) {
        this.entityKey = entityKey;
    }

    /**
     * Getter for <code>erp_marcato.views.data</code>.
     */
    public JSONB getData() {
        return this.data;
    }

    /**
     * Setter for <code>erp_marcato.views.data</code>.
     */
    public void setData(JSONB data) {
        this.data = data;
    }

    /**
     * Getter for <code>erp_marcato.views.workspace_id</code>.
     */
    public UUID getWorkspaceId() {
        return this.workspaceId;
    }

    /**
     * Setter for <code>erp_marcato.views.workspace_id</code>.
     */
    public void setWorkspaceId(UUID workspaceId) {
        this.workspaceId = workspaceId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Views other = (Views) obj;
        if (this.viewId == null) {
            if (other.viewId != null)
                return false;
        }
        else if (!this.viewId.equals(other.viewId))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.entityKey == null) {
            if (other.entityKey != null)
                return false;
        }
        else if (!this.entityKey.equals(other.entityKey))
            return false;
        if (this.data == null) {
            if (other.data != null)
                return false;
        }
        else if (!this.data.equals(other.data))
            return false;
        if (this.workspaceId == null) {
            if (other.workspaceId != null)
                return false;
        }
        else if (!this.workspaceId.equals(other.workspaceId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.viewId == null) ? 0 : this.viewId.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.entityKey == null) ? 0 : this.entityKey.hashCode());
        result = prime * result + ((this.data == null) ? 0 : this.data.hashCode());
        result = prime * result + ((this.workspaceId == null) ? 0 : this.workspaceId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Views (");

        sb.append(viewId);
        sb.append(", ").append(label);
        sb.append(", ").append(entityKey);
        sb.append(", ").append(data);
        sb.append(", ").append(workspaceId);

        sb.append(")");
        return sb.toString();
    }
}
