/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.enums;


import com.marcato.springmarcatoerp.entity.ErpMarcato;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum RoleLevel implements EnumType {

    INTERN("INTERN"),

    TRAINEE("TRAINEE"),

    JUNIOR("JUNIOR"),

    MIDDLE("MIDDLE"),

    SENIOR("SENIOR");

    private final String literal;

    private RoleLevel(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return ErpMarcato.ERP_MARCATO;
    }

    @Override
    public String getName() {
        return "role_level";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static RoleLevel lookupLiteral(String literal) {
        return EnumType.lookupLiteral(RoleLevel.class, literal);
    }
}
