/*
 * This file is generated by jOOQ.
 */
package com.marcato.springmarcatoerp.entity.enums;


import com.marcato.springmarcatoerp.entity.ErpMarcato;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum Status implements EnumType {

    INACTIVE("INACTIVE"),

    ACTIVE("ACTIVE");

    private final String literal;

    private Status(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return ErpMarcato.ERP_MARCATO;
    }

    @Override
    public String getName() {
        return "status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static Status lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Status.class, literal);
    }
}
